import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
const readCss = async () => (await Promise.all(['tokens-base','feature-components','pages-polish'].map(f => readFile(`apps/lab-web/src/css/${f}.css`, 'utf8')))).join('\n');

test('static app declares module entry and product identity',async()=>{const html=await readFile('apps/lab-web/src/index.html','utf8');const js=await readFile('apps/lab-web/src/experiment-controls.js','utf8');const pkg=JSON.parse(await readFile('package.json','utf8'));assert.match(html,/type="module" src="app\.js"/);assert.match(html,new RegExp('application-version" content="'+pkg.version.replace(/\./g,'\\.')+'"'));assert.match(html,new RegExp('"softwareVersion": "'+pkg.version.replace(/\./g,'\\.')+'"'));assert.match(js,/Advanced Core/);});
test('landing page container and routes are present',async()=>{const html=await readFile('apps/lab-web/src/index.html','utf8');const js=await readFile('apps/lab-web/src/app.js','utf8');assert.match(html,/id="landing-app"/);assert.match(js,/LANDING_MODES/);assert.match(js,/import \{ renderRulesPage \} from '.\/rulebook-renderer\.js'/);});
test('rulebook-renderer exports renderMarkdown and renderRulesPage',async()=>{const js=await readFile('apps/lab-web/src/rulebook-renderer.js','utf8');assert.match(js,/export function renderMarkdown/);assert.match(js,/export async function renderRulesPage/);});
test('styles.css has landing, play, and rules page styles',async()=>{const css=await readCss();assert.match(css,/\.landing-app/);assert.match(css,/\.rules-page/);assert.match(css,/\.rules-toc/);assert.match(css,/\.rules-content/);});
test('browser worker executes certified replay verification and Advanced Core campaigns',async()=>{const text=await readFile('apps/lab-web/src/worker.js','utf8');assert.match(text,/verifyCertifiedReplay/);assert.match(text,/verify-corpus-result/);assert.match(text,/run-autonomy-campaign/);assert.match(text,/runBrowserPolicyMatch/);assert.doesNotMatch(text,/MOVE_CARD|SCORE_CARD|SUBMIT_CORE_PRIVATE_CHOICE/);});
test('reduced motion is supported',async()=>assert.match(await readCss(),/prefers-reduced-motion/));
test('browser engine build is narrow and Node-free',async()=>{const files=(await readdir('apps/lab-web/dist/engine')).sort();assert.ok(files.includes('browser-entry.js'));assert.ok(files.includes('hash.js'));assert.ok(!files.includes('index.js'));for(const file of files.filter(x=>x.endsWith('.js')))assert.doesNotMatch(await readFile(`apps/lab-web/dist/engine/${file}`,'utf8'),/node:/,file);});
test('browser SHA-256 shim passes standard vectors',async()=>{const {sha256Text}=await import('../apps/lab-web/dist/engine/hash.js');assert.equal(sha256Text(''),'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');assert.equal(sha256Text('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');});
test('static build declares Advanced Core browser engine and capability truth',async()=>{const info=JSON.parse(await readFile('apps/lab-web/dist/BUILD_INFO.json','utf8'));const rootPkg=JSON.parse(await readFile('package.json','utf8'));assert.equal(info.version,rootPkg.version);assert.equal(info.engineVersion,'4.2.6');assert.equal(info.rulesVersion,'4.3.1');assert.equal(info.buildKind,'UNRESTRICTED_CORE_PLAYER_RELEASE');assert.ok(info.certifiedReplayCount>=121,'certified replay count must be at least 121');assert.ok((await stat('apps/lab-web/dist/policy-scoring.js')).size>1000);const capability=JSON.parse(await readFile('apps/lab-web/dist/data/release/capability-manifest.json','utf8'));assert.equal(capability.profiles.find(p=>p.profileId==='CORE_ADVANCED_2P').autonomy,'SUPPORTED');assert.equal(capability.unsupportedCombinations.find(x=>x.kind==='COMPLETE_CORE_AUTONOMY').status,'SUPPORTED');assert.equal(capability.profiles.find(p=>p.profileId==='CORE_UNRESTRICTED_2P').autonomy,'SUPPORTED');assert.equal(capability.profiles.find(p=>p.profileId==='CORE_UNRESTRICTED_2P').engineProfileId,'core-unrestricted-authority');});

