import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
async function files(dir){let out=[];for(const e of await readdir(dir,{withFileTypes:true})){if(e.name==='node_modules')continue;const p=path.join(dir,e.name);if(e.isDirectory())out=out.concat(await files(p));else out.push(p);}return out;}
test('policy package cannot import raw engine surfaces',async()=>{for(const file of await files('packages/policies')){const text=await readFile(file,'utf8');assert.doesNotMatch(text,/runtime\/(?:vendor|autonomy-engine)-dist|EngineCommand|MOVE_CARD|SCORE_CARD|SUBMIT_CORE_PRIVATE_CHOICE/);}});
test('web app cannot import mutation helpers directly',async()=>{for(const file of await files('apps/lab-web/src')){const text=await readFile(file,'utf8');assert.doesNotMatch(text,/from\s+['"][^'"]*(runtime\/(?:vendor|autonomy-engine)-dist|runtime\/[^'"]*\/state\.js|runtime\/[^'"]*\/engine\.js)['"]/);}});
test('only engine adapter imports compiled engine runtime',async()=>{for(const file of await files('packages')){if(file.includes('engine-adapter'))continue;const text=await readFile(file,'utf8');assert.doesNotMatch(text,/runtime\/(?:vendor|autonomy-engine)-dist/);}});
test('capability manifest exposes only audited Lab aliases and remains fail-closed',async()=>{const x=JSON.parse(await readFile('reports/capability-manifest.json','utf8'));const patch=JSON.parse(await readFile('upstream/intrilex-engine-4.2.6-attachment-integrity-hotfix/PRIORITY_PASS_HOTFIX_MANIFEST.json','utf8'));assert.equal(x.surfaces.legalActionEnumeration,true);assert.equal(x.surfaces.completeMatchOrchestration,true);assert.equal(x.defaultSimulationProfile,'core-advanced-authority');const supported=x.profiles.filter(p=>p.autonomy==='SUPPORTED').map(p=>p.profileId).sort();assert.deepEqual(supported,['CORE_ADVANCED_2P','CORE_UNRESTRICTED_2P','FIRST_CONTACT_GENERIC_2P']);assert.equal(x.unsupportedCombinations.find(i=>i.kind==='COMPLETE_CORE_AUTONOMY').status,'SUPPORTED');assert.equal(x.unsupportedCombinations.find(i=>i.kind==='OPTIONAL_MODULE_AUTONOMY').status,'BLOCKED');assert.equal(x.unsupportedCombinations.find(i=>i.kind==='MULTIPLAYER_AUTONOMY').status,'BLOCKED');assert.equal(x.interruptRuling.keywordTax,false);assert.equal(x.engine.patch.payloadHash,patch.payloadHash);assert.equal(x.engine.patch.fileCount,patch.fileCount);assert.equal(x.labVersion,'0.31.0','labVersion must match version.js');const unrestricted=x.profiles.find(p=>p.profileId==='CORE_UNRESTRICTED_2P');assert.ok(unrestricted,'unrestricted profile must exist');assert.equal(unrestricted.engineProfileId,'core-unrestricted-authority');assert.equal(unrestricted.actionCoverage.covered.includes('hidden-choice-supers'),true,'hidden supers must be covered');assert.equal(unrestricted.actionCoverage.covered.includes('sudden-death'),true,'sudden death must be covered');assert.equal(unrestricted.actionCoverage.covered.includes('generated-effect-copy'),true,'generated effect copy must be covered');assert.equal(unrestricted.actionCoverage.replayOnly.length,0,'unrestricted profile must have no replayOnly items');});
test('unrestricted core profile completes a full match via engine adapter',async()=>{const adapter=await import('../packages/engine-adapter/src/adapter.mjs');const{CORE_UNRESTRICTED_AUTHORITY_PROFILE,createSimulationState,createSimulationDecisionFrame,executeSimulationAction}=adapter;let state=createSimulationState({profileId:CORE_UNRESTRICTED_AUTHORITY_PROFILE.id,playerIds:['P1','P2'],seatOrder:['P1','P2'],enabledModules:[],seed:42});assert.equal(state.metadata.coreAuthority.profileId,'core-unrestricted-authority');let decisions=0;const families=new Set();while(decisions<600){const frame=createSimulationDecisionFrame(state);if(frame.status!=='PLAYER_DECISION_REQUIRED'){assert.equal(frame.status,'TERMINAL','match must terminate cleanly');assert.ok(['NORMAL_VICTORY','EXHAUSTED_RESOLUTION','CANONICAL_DRAW','SUDDEN_DEATH_RESOLUTION'].includes(frame.reasonCode),'match must end with a valid terminal reason, got: '+frame.reasonCode);break;}state=frame.state;const actions=frame.legalActionFrame.actions;let action=actions.find(a=>a.family==='phase'&&a.mode==='enter-action')??actions.find(a=>a.family!=='swap-bar')??actions[0];families.add(action.family+':'+(action.mode??'none'));const command=frame.resolve(action.actionId);const result=executeSimulationAction(state,command);if(!result.accepted){let found=false;for(const a of actions){if(a.actionId===action.actionId)continue;try{const cmd=frame.resolve(a.actionId);const r=executeSimulationAction(state,cmd);if(r.accepted){state=r.state;found=true;break;}}catch(e){}}if(!found)break;}else{state=result.state;}decisions++;}assert.ok(decisions>10,'match must last more than 10 decisions');assert.ok(families.size>=5,'match must exercise at least 5 distinct action families');});
test('browser entry exports unrestricted core profile',async()=>{const entry=await readFile('apps/lab-web/dist/engine/browser-entry.js','utf8');assert.ok(entry.includes('CORE_UNRESTRICTED_AUTHORITY_PROFILE'),'browser-entry.js must export CORE_UNRESTRICTED_AUTHORITY_PROFILE');const core=await readFile('apps/lab-web/dist/engine/core-advanced.js','utf8');assert.ok(core.includes('core-unrestricted-authority'),'core-advanced.js must define the unrestricted profile id');});
// IRX-M23: projectFrame must never return raw engine state for any mode.
// Spectator mode must use publicStateView (hides seed, RNG, hands).
// Unknown modes must throw — fail-closed, never fall through to raw state.
test('IRX-M23: projectFrame spectator mode hides seed/RNG and unknown modes throw',async()=>{const adapter=await import('../packages/engine-adapter/src/adapter.mjs');const{CORE_UNRESTRICTED_AUTHORITY_PROFILE,createSimulationState,projectFrame}=adapter;const state=createSimulationState({profileId:CORE_UNRESTRICTED_AUTHORITY_PROFILE.id,playerIds:['P1','P2'],seatOrder:['P1','P2'],enabledModules:[],seed:42});const frame={state};
// Public mode must not expose seed
const pubView=projectFrame(frame,'public','P1');const pubJson=JSON.stringify(pubView);assert.ok(!pubJson.includes('"seed"'),'public view must not expose seed');
// Spectator mode must not expose seed or RNG (must use publicStateView, not raw state)
const specView=projectFrame(frame,'spectator','S1');const specJson=JSON.stringify(specView);assert.ok(!specJson.includes('"seed"'),'spectator view must not expose seed');assert.ok(!specJson.includes('"rng"'),'spectator view must not expose rng state');
// Unknown mode must throw — never return raw frame.state
assert.throws(()=>projectFrame(frame,'raw','P1'),/Unknown projection mode/,'unknown mode must throw');assert.throws(()=>projectFrame(frame,undefined,'P1'),/Unknown projection mode/,'undefined mode must throw');assert.throws(()=>projectFrame(frame,'admin','P1'),/Unknown projection mode/,'admin mode must throw');});

