import test from 'node:test';
import assert from 'node:assert/strict';
import { createSimulationState, createSimulationDecisionFrame } from '@intrilex/engine-adapter';
import { runPolicyMatch } from '@intrilex/simulation-runtime';
import { emptySemanticCounters, applyDecisionCounters, applyEventCounters, semanticClassForAction } from '@intrilex/telemetry';
const setup=profileId=>({profileId,playerIds:['P1','P2'],seatOrder:['P1','P2'],enabledModules:[],eventApprovedModules:[],seed:1});
test('ordinary action frames expose no ordinary Pass',()=>{for(const profile of ['core-advanced-authority','first-contact-trigger-closure']){const frame=createSimulationDecisionFrame(createSimulationState(setup(profile)));assert.equal(frame.policyActions.some(a=>a.family==='pass'),false,profile);assert.equal(frame.policyActions.some(a=>a.family==='exhausted-pass'),false,profile);}});
test('semantic counters separate response decline from actions and orchestration',()=>{const c=emptySemanticCounters();const decline={actionId:'response-decline:x',family:'response-decline',mode:'decline',timingClass:'INSTANT'};const counter={actionId:'counter:x',family:'counter',mode:'ace',timingClass:'INSTANT'};applyDecisionCounters(c,decline,[counter,decline]);applyEventCounters(c,[{type:'CORE_AUTOMATIC_PRIORITY_ADVANCE'},{type:'CORE_RESPONSE_WINDOW_CLOSED'}]);assert.equal(c.policyDecisionCount,1);assert.equal(c.policyActionCount,0);assert.equal(c.actionCount,0);assert.equal(c.passActionCount,0);assert.equal(c.responseDeclinedWithOptionsCount,1);assert.equal(c.automaticPriorityAdvanceCount,1);assert.equal(c.responseWindowClosedCount,1);assert.equal(semanticClassForAction(decline),'response-decline');});
test('real match preserves semantic accounting and observer invariance',()=>{const on=runPolicyMatch({seed:1,ordinal:1,profileId:'core-advanced-authority',seatOrder:['P1','P2'],policyIds:['random-legal','random-legal'],decisionLimit:1800,telemetryEnabled:true});const off=runPolicyMatch({seed:1,ordinal:1,profileId:'core-advanced-authority',seatOrder:['P1','P2'],policyIds:['random-legal','random-legal'],decisionLimit:1800,telemetryEnabled:false});assert.equal(on.summary.matchResultHash,off.summary.matchResultHash);assert.equal(on.summary.finalStateHash,off.summary.finalStateHash);assert.equal(on.summary.passActionCount,on.summary.exhaustedPassActionCount);assert.ok(on.summary.responseDeclinedWithOptionsCount>0);assert.ok(on.summary.automaticPriorityAdvanceCount>0);assert.ok(on.facts.decisionFacts.filter(f=>f.semanticClass==='response-decline').every(f=>f.hadLawfulResponse&&!f.consumedMiniTurn&&!f.createdSkip));});
