// ═══════════════════════════════════════════════════════════════
// v0.21.0-browser-version-parity.test.mjs
// Version-drift guard — ensures no hardcoded rules/engine version
// string literals exist in the browser app source.
//
// The v0.21.0 release ("Full Rank Authority Reconciliation") bumped
// all version surfaces to Official Rules v4.3.1. This test prevents
// regression: browser files must import from version.js, not hardcode
// version strings.
// ═══════════════════════════════════════════════════════════════
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'apps/lab-web/src');

// Stale version strings that must never appear as literals in browser source.
// These were the pre-v0.21.0 values that were incompletely reconciled.
// Note: 4.2.0 is a legitimate analytics schema version, so we only flag it
// when used as a rules/engine version (e.g. RULES_VERSION = '4.2.0'),
// not when used as an analytics schema version constant.
const STALE_VERSION_PATTERNS = [
  { pattern: /['"`]4\.1\.2['"`]/, label: 'rules 4.1.2' },
];
const STALE_RULES_ASSIGNMENT_PATTERNS = [
  { pattern: /(?:RULES_VERSION|ENGINE_VERSION)\s*=\s*['"`]4\.2\.0['"`]/, label: 'rules/engine 4.2.0 assignment' },
];

// Files exempt from the scan (auto-generated or non-source)
const EXEMPT_FILES = new Set([
  'version.js',       // auto-generated by scripts/generate-version.mjs
]);

/**
 * Recursively collect all .js files under a directory.
 */
async function collectJsFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectJsFiles(fullPath));
    } else if (entry.name.endsWith('.js') && !EXEMPT_FILES.has(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

test('Browser version parity: no stale 4.1.2 or 4.2.0 string literals in apps/lab-web/src', async () => {
  const files = await collectJsFiles(srcDir);
  assert.ok(files.length > 0, 'expected to find .js files in apps/lab-web/src');

  const violations = [];
  for (const file of files) {
    const content = await readFile(file, 'utf8');
    for (const { pattern, label } of STALE_VERSION_PATTERNS) {
      const matches = content.match(pattern);
      if (matches) {
        const rel = path.relative(root, file);
        violations.push(`${rel}: found stale ${label} literal`);
      }
    }
    for (const { pattern, label } of STALE_RULES_ASSIGNMENT_PATTERNS) {
      const matches = content.match(pattern);
      if (matches) {
        const rel = path.relative(root, file);
        violations.push(`${rel}: found stale ${label}`);
      }
    }
  }

  assert.equal(violations.length, 0,
    `Stale version string literals found (must import from version.js instead):\n${violations.join('\n')}`);
});

test('Browser version parity: version.js exports RULES_VERSION matching release identity', async () => {
  const identity = JSON.parse(await readFile(path.join(root, 'config/release-identity.json'), 'utf8'));
  const versionContent = await readFile(path.join(srcDir, 'version.js'), 'utf8');

  // version.js is auto-generated and uses double-quoted strings
  const rulesMatch = versionContent.match(/export\s+const\s+RULES_VERSION\s*=\s*"([^"]+)"/);
  assert.ok(rulesMatch, 'version.js must export RULES_VERSION');
  assert.equal(rulesMatch[1], identity.rulesVersion,
    `version.js RULES_VERSION "${rulesMatch[1]}" != release identity "${identity.rulesVersion}"`);

  const engineMatch = versionContent.match(/export\s+const\s+ENGINE_VERSION\s*=\s*"([^"]+)"/);
  assert.ok(engineMatch, 'version.js must export ENGINE_VERSION');
  assert.equal(engineMatch[1], identity.engineVersion,
    `version.js ENGINE_VERSION "${engineMatch[1]}" != release identity "${identity.engineVersion}"`);
});

test('Browser version parity: save-integrity.js RULES_VERSION matches release identity', async () => {
  const identity = JSON.parse(await readFile(path.join(root, 'config/release-identity.json'), 'utf8'));
  const saveIntegrityContent = await readFile(path.join(srcDir, 'play/save-integrity.js'), 'utf8');

  const rulesMatch = saveIntegrityContent.match(/export\s+const\s+RULES_VERSION\s*=\s*'([^']+)'/);
  assert.ok(rulesMatch, 'save-integrity.js must export RULES_VERSION');
  assert.equal(rulesMatch[1], identity.rulesVersion,
    `save-integrity.js RULES_VERSION "${rulesMatch[1]}" != release identity "${identity.rulesVersion}"`);
});
