// ═══════════════════════════════════════════════════════════════
// v1.0.0-certified-baseline.test.mjs
// Certification tests for the v1.0.0 Certified Public Baseline.
//
// This is NOT a feature test suite. It verifies that the six
// certification gate dimensions from ROADMAP Phase 7 all pass,
// and that the codebase is stable and trustworthy enough to be
// labelled v1.0.0.
// ═══════════════════════════════════════════════════════════════

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');

function readJson(p) { return JSON.parse(readFileSync(join(ROOT, p), 'utf8')); }
function readText(p) { return readFileSync(join(ROOT, p), 'utf8'); }
function exists(p) { return existsSync(join(ROOT, p)); }

// ── Gate 1: Rules & Engine ──────────────────────────────────────

test('v1.0.0 cert: rules and engine versions agree across all surfaces', () => {
  const ri = readJson('config/release-identity.json');
  const em = readJson('config/engine-manifest.json');
  const ct = readJson('config/capability-truth.json');
  const engineVersions = new Set([ri.engineVersion, em.engineVersion, ct.product.engineVersion].filter(Boolean));
  const rulesVersions = new Set([ri.rulesVersion, em.rulesVersion, ct.product.rulesVersion].filter(Boolean));
  assert.equal(engineVersions.size, 1, `Engine versions must agree: ${[...engineVersions].join(', ')}`);
  assert.equal(rulesVersions.size, 1, `Rules versions must agree: ${[...rulesVersions].join(', ')}`);
});

// Note: self-audit status, canon defect gate, determinism mismatch gate, hidden info leak gate,
// and false analytic claim gate are verified by the certification gate runner
// (scripts/certification-gates.mjs) AFTER the self-audit completes, to avoid a circular
// dependency where the test checks the report being generated by the same run.

test('v1.0.0 cert: engine adapter exports legal action enumeration', () => {
  assert.ok(exists('packages/engine-adapter/src/adapter.mjs'), 'Engine adapter must exist');
});

test('v1.0.0 cert: balance findings rerun after correctness repairs', () => {
  assert.ok(exists('reports/balance-check'), 'Balance check reports must exist');
});

// ── Gate 2: Local Player Experience ─────────────────────────────

test('v1.0.0 cert: new player onboarding (Academy) exists', () => {
  assert.ok(exists('apps/lab-web/src/play/academy/academy-controller.mjs'), 'Academy must exist');
});

test('v1.0.0 cert: local AI matches stable (HYBRIX agent + policy adapter)', () => {
  assert.ok(exists('packages/game-ai/src/agent.mjs'), 'HYBRIX agent must exist');
  assert.ok(exists('packages/game-ai/src/policy-adapter.mjs'), 'Policy adapter must exist');
});

test('v1.0.0 cert: saves, resumes, imports, exports, replays stable', () => {
  const si = readText('apps/lab-web/src/play/save-integrity.js');
  assert.ok(si.includes('PRODUCT_VERSION'), 'Save integrity must check PRODUCT_VERSION');
  assert.ok(si.includes('INCOMPATIBLE_PRODUCT_VERSION'), 'Save integrity must have compatibility explanation');
});

test('v1.0.0 cert: replay system exists', () => {
  assert.ok(exists('packages/replay-caster/src/caster-session.mjs'), 'Replay Caster must exist');
});

test('v1.0.0 cert: puzzle ladder exists with progress tracking', () => {
  assert.ok(exists('apps/lab-web/src/play/puzzle/puzzle-progress.mjs'), 'Puzzle progress must exist');
});

test('v1.0.0 cert: accessibility certified (keyboard, mobile, reduced-motion, high-contrast)', () => {
  assert.ok(exists('test/accessibility.test.mjs'), 'Accessibility test suite must exist');
});

test('v1.0.0 cert: bounded lookahead AI exists and is not labelled expert', () => {
  const bl = readText('packages/game-ai/src/bounded-lookahead.mjs');
  assert.ok(bl.includes('LOOKAHEAD_STRENGTH_TIER'), 'Lookahead strength tier must be defined');
  assert.ok(!bl.toLowerCase().includes("'expert'"), 'Lookahead must NOT be labelled "expert"');
});

// ── Gate 3: Online Experience ───────────────────────────────────

test('v1.0.0 cert: ranked season lifecycle proven', () => {
  assert.ok(exists('scripts/provision-season.mjs'), 'Season provisioning CLI must exist');
});

test('v1.0.0 cert: auth and reconnect tested', () => {
  assert.ok(exists('test/auth-reconnect.test.mjs'), 'Auth reconnect tests must exist');
});

test('v1.0.0 cert: matchmaking and ranked admission', () => {
  assert.ok(exists('apps/match-server/src/server.mjs'), 'Match server must exist');
});

test('v1.0.0 cert: spectator projection (delayed broadcast)', () => {
  assert.ok(exists('apps/match-server/src/broadcast/delayed-broadcast-buffer.mjs'), 'Delayed broadcast must exist');
});

test('v1.0.0 cert: rated matches with abandonment handling', () => {
  assert.ok(exists('apps/match-server/src/ranked/abandonment-handler.mjs'), 'Abandonment handler must exist');
});

test('v1.0.0 cert: durable persistence (outbox/migration)', () => {
  const hasOutbox = exists('apps/match-server/src/persistence/terminal-outbox.mjs');
  const hasMigration = exists('apps/match-server/src/persistence/migration-runner.mjs');
  assert.ok(hasOutbox || hasMigration, 'Durable persistence must exist');
});

test('v1.0.0 cert: automated backup', () => {
  assert.ok(exists('scripts/backup-match-db.mjs'), 'Backup script must exist');
});

test('v1.0.0 cert: monitoring (health endpoint)', () => {
  const server = readText('apps/match-server/src/server.mjs');
  assert.ok(server.includes('/api/status'), 'Health monitoring endpoint must exist');
});

test('v1.0.0 cert: abuse controls (moderation)', () => {
  assert.ok(exists('apps/match-server/src/moderation/moderation-service.mjs'), 'Moderation service must exist');
});

test('v1.0.0 cert: privacy threat model current', () => {
  assert.ok(exists('test/privacy.test.mjs'), 'Privacy tests must exist');
  assert.ok(exists('test/privacy-matrix.test.mjs'), 'Privacy matrix must exist');
});

test('v1.0.0 cert: tournament infrastructure', () => {
  assert.ok(exists('packages/account-domain/src/tournament-operations.mjs'), 'Tournament operations must exist');
});

// ── Gate 4: Laboratory ──────────────────────────────────────────

test('v1.0.0 cert: stable identifiers (deterministic beat IDs)', () => {
  const schemas = readText('packages/replay-caster/src/schemas.mjs');
  assert.ok(schemas.includes('makeBeatId'), 'Beat ID derivation must exist');
  assert.ok(schemas.includes('hashCanonical'), 'Deterministic hashing must be used');
});

test('v1.0.0 cert: evidence epoch and limitations recorded', () => {
  assert.ok(exists('packages/statistics/src/evidence-honest.mjs'), 'Evidence-honest intelligence must exist');
});

test('v1.0.0 cert: generated reports reproducible', () => {
  assert.ok(exists('scripts/generate-effect-power-rankings.mjs'), 'Report generation must exist');
});

test('v1.0.0 cert: stale conclusions invalidated after authority changes', () => {
  const inv = readText('packages/replay-caster/src/investigation-workflow.mjs');
  assert.ok(inv.includes('checkInvalidation'), 'Invalidation check must exist');
  assert.ok(inv.includes('INVALIDATED'), 'INVALIDATED status must exist');
});

test('v1.0.0 cert: commentary contract (fact-level authorization)', () => {
  assert.ok(exists('packages/replay-caster/src/commentary-contract.mjs'), 'Commentary contract must exist');
});

test('v1.0.0 cert: brain topology (mechanic/evidence topology explorer)', () => {
  assert.ok(exists('apps/lab-web/src/brain/brain-topology.mjs'), 'Brain topology must exist');
});

// ── Gate 5: Release Engineering ─────────────────────────────────

test('v1.0.0 cert: clean-room install and build', () => {
  assert.ok(exists('scripts/verify-clean-room.mjs'), 'Clean-room verification must exist');
});

test('v1.0.0 cert: deterministic build verification', () => {
  assert.ok(exists('scripts/build.mjs'), 'Build script must exist');
});

test('v1.0.0 cert: full CI on supported environments', () => {
  assert.ok(exists('scripts/ci.mjs'), 'CI script must exist');
});

test('v1.0.0 cert: secret scan (fail-closed)', () => {
  assert.ok(exists('scripts/secret-containment-scan.mjs'), 'Secret containment scan must exist');
});

test('v1.0.0 cert: release identity manifest with verification', () => {
  assert.ok(exists('config/release-identity.json'), 'Release identity must exist');
  assert.ok(exists('scripts/generate-release-identity.mjs'), 'Release identity generator must exist');
});

test('v1.0.0 cert: engine authority manifest with verification', () => {
  assert.ok(exists('config/engine-manifest.json'), 'Engine manifest must exist');
  assert.ok(exists('scripts/generate-engine-manifest.mjs'), 'Engine manifest generator must exist');
});

test('v1.0.0 cert: capability truth manifest exists', () => {
  assert.ok(exists('config/capability-truth.json'), 'Capability truth must exist');
});

test('v1.0.0 cert: all version surfaces agree', () => {
  const ri = readJson('config/release-identity.json');
  const pkg = readJson('package.json');
  const versionJs = readText('apps/lab-web/src/version.js');
  const versionMjs = readText('packages/shared/src/version.mjs');
  const v1 = ri.version;
  const v2 = pkg.version;
  const v3 = versionJs.match(/LAB_VERSION\s*=\s*['"]([^'"]+)['"]/)?.[1];
  const v4 = versionMjs.match(/LAB_VERSION\s*=\s*['"]([^'"]+)['"]/)?.[1];
  assert.equal(v2, v1, `package.json ${v2} != release-identity ${v1}`);
  assert.equal(v3, v1, `version.js ${v3} != release-identity ${v1}`);
  assert.equal(v4, v1, `version.mjs ${v4} != release-identity ${v1}`);
});

test('v1.0.0 cert: no untracked debug ambiguity (.gitignore exists)', () => {
  assert.ok(exists('.gitignore'), '.gitignore must exist');
});

// ── Gate 6: Human Validation ────────────────────────────────────

test('v1.0.0 cert: human validation protocol documented', () => {
  const roadmap = readText('docs/ROADMAP.md');
  assert.ok(roadmap.includes('Human validation'), 'Human validation protocol must be documented');
  assert.ok(roadmap.includes('structured sessions'), 'Structured sessions must be documented');
});

test('v1.0.0 cert: human validation measurement criteria defined', () => {
  const roadmap = readText('docs/ROADMAP.md');
  const criteria = ['start a correct match', 'action is unavailable', 'priority and response windows', 'recover from disconnection', 'replay and inspect'];
  for (const c of criteria) {
    assert.ok(roadmap.includes(c), `Measurement criterion "${c}" must be documented`);
  }
});

test('v1.0.0 cert: Academy supports new player validation session', () => {
  assert.ok(exists('apps/lab-web/src/play/academy/academy-controller.mjs'), 'Academy must exist for new player sessions');
});

test('v1.0.0 cert: investigation workflow supports suspicious decision inspection', () => {
  assert.ok(exists('packages/replay-caster/src/investigation-workflow.mjs'), 'Investigation workflow must exist');
});

test('v1.0.0 cert: interface legibility gate documented', () => {
  const roadmap = readText('docs/ROADMAP.md');
  assert.ok(roadmap.includes('interface teach the game'), 'Interface legibility gate must be documented');
});

// ── Certification gate framework ────────────────────────────────

test('v1.0.0 cert: certification gate framework has 6 gates', async () => {
  const { CERTIFICATION_GATES } = await import('../scripts/certification-gates.mjs');
  assert.equal(Object.keys(CERTIFICATION_GATES).length, 6, 'Must have exactly 6 certification gates');
  const expectedKeys = ['rules-engine', 'local-experience', 'online-experience', 'laboratory', 'release-engineering', 'human-validation'];
  for (const key of expectedKeys) {
    assert.ok(CERTIFICATION_GATES[key], `Gate ${key} must exist`);
    assert.ok(typeof CERTIFICATION_GATES[key].fn === 'function', `Gate ${key} must have a function`);
    assert.ok(CERTIFICATION_GATES[key].name, `Gate ${key} must have a name`);
  }
});

test('v1.0.0 cert: each gate returns structured result with evidence', async () => {
  const { CERTIFICATION_GATES } = await import('../scripts/certification-gates.mjs');
  for (const [key, gate] of Object.entries(CERTIFICATION_GATES)) {
    const result = gate.fn();
    assert.ok(typeof result.passed === 'boolean', `Gate ${key} must return boolean passed`);
    assert.ok(Array.isArray(result.evidence), `Gate ${key} must return evidence array`);
    assert.ok(Array.isArray(result.gaps), `Gate ${key} must return gaps array`);
    assert.ok(result.evidence.length > 0, `Gate ${key} must have at least one evidence item`);
  }
});
