// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const LAB_VERSION = "0.24.2";
export const ENGINE_VERSION = "4.2.6";
export const RULES_VERSION = "4.3.1";
export const OFFICIAL_RULES_VERSION = "4.3.1";
export const SCHEMA_VERSION = "4.1.0";
