import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { canonicalize } from "./canonical-json.js";
import { loadFixtures } from "./conformance.js";
import { parseCertifiedReplay, verifyCertifiedReplay } from "./phase16.js";
import { DEFAULT_INTEGRATION_SCENARIOS, runIntegrationScenarios } from "./phase18.js";

const CERTIFIED_BASE_VERSION="4.1.0";
const RULES_AUTHORITY_VERSION="4.1.1";
const HISTORICAL_V410_PHASE218_AGGREGATE="994faf051dfa9441dd6511d360caa79a8b534b9db90908055e9692d6952f896a";
const PRESERVED_AGGREGATE="e754dfc25e171bdd60a6d41025b42afd3e8120e0ae210c68b02d51d11bfeb211";
const HISTORICAL_V410_AGGREGATE="05f67133eab3f8e92d526db17b25407842204e0eeea3a605bd417d0479805547";
const FINAL_AGGREGATE="8c91e8194e7fa3ab6bbb3eaa6946a97efd70343c36d5e5953ee8e1c0357013df";
const PHASE16_IDS=["CT-091","CT-109","CT-116","CT-120"];
const PHASE17_IDS=["CT-005","CT-014","CT-022","CT-024","CT-031","CT-094","CT-097","CT-115","CT-120"];
const PHASE18_IDS=["CT-001","CT-002","CT-003","CT-004","CT-005","CT-014","CT-017","CT-025","CT-089","CT-103","CT-104","CT-105","CT-117","CT-118","CT-119"];
const PHASE20_IDS=["CT-013","CT-021","CT-023","CT-034","CT-035"];
type Check={name:string;status:"PASS"|"FAIL";detail:string};
type Report={failed?:number;deterministic?:boolean;fixtureCount?:number;aggregateHash?:string;engineVersion?:string;fixtures?:Array<{id:string}>};

async function walk(root:string,current=root):Promise<string[]>{ const entries=await readdir(current,{withFileTypes:true}); const files:string[]=[]; for(const entry of entries.sort((a,b)=>a.name.localeCompare(b.name))){ if([".git","node_modules","dist"].includes(entry.name))continue; const full=path.join(current,entry.name); if(entry.isDirectory())files.push(...await walk(root,full)); else files.push(path.relative(root,full).replaceAll(path.sep,"/")); } return files; }
async function sha256File(file:string):Promise<string>{const hash=createHash("sha256");hash.update(await readFile(file));return hash.digest("hex");}
function idsEqual(actual:string[],expected:string[]):boolean{return canonicalize(actual)===canonicalize(expected);}
async function json<T>(file:string):Promise<T>{return JSON.parse(await readFile(file,"utf8")) as T;}

export async function validateRelease(projectRoot:string):Promise<{verdict:"PASS"|"FAIL";checks:Check[]}>{
 const checks:Check[]=[];
 const required=[
  "README.md","package.json","tsconfig.json","src/engine.ts","src/phase20.ts","src/replay.ts","src/phase16.ts","src/phase17.ts","src/phase18.ts","src/simulation.ts","src/certification.ts",
  "tools/independent_replay_verifier.py","fixtures/phase16-rng-vectors.json","fixtures/phase20-canonical-closure.json",
  "docs/INTRILEX_v4.1_COMPLETE_PLAYER_RULEBOOK.md","canonical/INTRILEX_v4.1_COMPLETE_PLAYER_RULEBOOK.md","docs/REPLAY_FORMAT.md","docs/JUDGE_TOOLS.md","docs/MODULE_INTEGRATION.md","docs/CANONICAL_FIXTURE_PROVENANCE.md","docs/BALANCE_SIMULATION.md","docs/FINAL_RELEASE_CERTIFICATION.md","docs/ROADMAP_COMPLETION_STATUS.md",
  "canonical/INTRILEX_v4.1_CANON_LOCK.json","canonical/IMPLEMENTATION_STATUS_PHASE_16.json","canonical/IMPLEMENTATION_STATUS_PHASE_17.json","canonical/IMPLEMENTATION_STATUS_PHASE_18.json","canonical/IMPLEMENTATION_STATUS_PHASE_19.json","canonical/IMPLEMENTATION_STATUS_PHASE_20.json",
  "reports/conformance-report.json","reports/phase2-18-regression-report.json","reports/phase20-canonical-closure-report.json","reports/phase16-replay-serialization-rng-report.json","reports/phase17-judge-tools-report.json","reports/phase18-integration-report.json","reports/phase19-balance-simulation-report.json","reports/independent-python-replay-verification.json","reports/final-release-certification.json","reports/BUILD_PROOF.md","HOTFIX_NOTICE_v4.1.1_INTERRUPT_TIMING.md","canonical/INTRILEX_v4.1.1_INTERRUPT_TIMING_HOTFIX.json"
 ];
 for(const rel of required){try{const size=(await stat(path.join(projectRoot,rel))).size;checks.push({name:`exists:${rel}`,status:size>0?"PASS":"FAIL",detail:`${size} bytes`});}catch(error){checks.push({name:`exists:${rel}`,status:"FAIL",detail:error instanceof Error?error.message:String(error)});}}
 try{const pkg=await json<{name?:string;version?:string;scripts?:Record<string,string>}>(path.join(projectRoot,"package.json"));const patchVersionOk=pkg.name==="@intrilex/headless-engine"&&/^4\.[12]\.\d+$/.test(pkg.version??"");checks.push({name:"package-rules-line-version",status:patchVersionOk?"PASS":"FAIL",detail:`${pkg.name??"missing"}@${pkg.version??"missing"}; certified-base=${CERTIFIED_BASE_VERSION}; rules-authority=${RULES_AUTHORITY_VERSION}`});const names=["test","conformance","judge","integration","simulate","verify:python","certify","validate"];checks.push({name:"ci-gate-shape",status:names.every(name=>pkg.scripts?.ci?.includes(`npm run ${name}`))?"PASS":"FAIL",detail:pkg.scripts?.ci??"missing"});}catch(error){checks.push({name:"package-json",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const preserved=await json<Report>(path.join(projectRoot,"reports/phase2-18-regression-report.json"));const ok=preserved.failed===0&&preserved.deterministic===true&&preserved.fixtureCount===116&&preserved.aggregateHash===PRESERVED_AGGREGATE&&preserved.engineVersion===CERTIFIED_BASE_VERSION;checks.push({name:"phase2-18-regression-preserved",status:ok?"PASS":"FAIL",detail:`fixtures=${preserved.fixtureCount}; aggregate=${preserved.aggregateHash}; engine=${preserved.engineVersion}`});}catch(error){checks.push({name:"phase2-18-regression-preserved",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const combined=await json<Report>(path.join(projectRoot,"reports/conformance-report.json"));const ok=combined.failed===0&&combined.deterministic===true&&combined.fixtureCount===121&&combined.aggregateHash===FINAL_AGGREGATE&&combined.engineVersion===CERTIFIED_BASE_VERSION;checks.push({name:"final-conformance",status:ok?"PASS":"FAIL",detail:`fixtures=${combined.fixtureCount}; aggregate=${combined.aggregateHash}; engine=${combined.engineVersion}`});}catch(error){checks.push({name:"final-conformance",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 for(const [name,rel,count,ids] of [["phase16","reports/phase16-replay-serialization-rng-report.json",4,PHASE16_IDS],["phase17","reports/phase17-judge-tools-report.json",9,PHASE17_IDS],["phase18","reports/phase18-integration-report.json",15,PHASE18_IDS],["phase20","reports/phase20-canonical-closure-report.json",5,PHASE20_IDS]] as const){try{const r=await json<Report>(path.join(projectRoot,rel));const actual=r.fixtures?.map(x=>x.id)??[];const ok=r.failed===0&&r.deterministic===true&&r.fixtureCount===count&&r.engineVersion===CERTIFIED_BASE_VERSION&&idsEqual(actual,[...ids]);checks.push({name:`${name}-gate`,status:ok?"PASS":"FAIL",detail:`fixtures=${r.fixtureCount}; ids=${actual.join(",")}; aggregate=${r.aggregateHash}`});}catch(error){checks.push({name:`${name}-gate`,status:"FAIL",detail:error instanceof Error?error.message:String(error)});}}
 try{const names=await readdir(path.join(projectRoot,"replays"));const legacy=names.filter(n=>n.endsWith(".replay.json")&&!n.includes(".certified.")&&!n.includes(".public.")).length;const legacyPublic=names.filter(n=>n.endsWith(".public.replay.json")).length;const certified=names.filter(n=>n.endsWith(".certified.replay.json")&&!n.endsWith(".public.certified.replay.json")).sort();const certifiedPublic=names.filter(n=>n.endsWith(".public.certified.replay.json")).length;let verified=0;for(const name of certified){verifyCertifiedReplay(parseCertifiedReplay(await readFile(path.join(projectRoot,"replays",name),"utf8")));verified++;}const ok=[legacy,legacyPublic,certified.length,certifiedPublic,verified].every(n=>n===121);checks.push({name:"replay-corpus",status:ok?"PASS":"FAIL",detail:`legacy=${legacy}+${legacyPublic}; certified=${certified.length}+${certifiedPublic}; verified=${verified}`});}catch(error){checks.push({name:"replay-corpus",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const integration=runIntegrationScenarios(DEFAULT_INTEGRATION_SCENARIOS);checks.push({name:"integration-matrix",status:integration.results.every(x=>x.status==="PASS")?"PASS":"FAIL",detail:`${integration.results.filter(x=>x.status==="PASS").length}/${integration.results.length}; ${integration.aggregateHash}`});}catch(error){checks.push({name:"integration-matrix",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const s=await json<{scenarioBaseline?:{scenarioCount?:number;commandCount?:number};fullMatchCampaign?:{matchCount?:number;campaignHash?:string;firstPlayerWin95?:number[]};deterministicReproduction?:{matched?:boolean}}>(path.join(projectRoot,"reports/simulation-baseline.json"));const ok=s.scenarioBaseline?.scenarioCount===121&&(s.scenarioBaseline.commandCount??0)>0&&(s.fullMatchCampaign?.matchCount??0)>=10000&&s.deterministicReproduction?.matched===true&&Array.isArray(s.fullMatchCampaign?.firstPlayerWin95);checks.push({name:"phase19-simulation",status:ok?"PASS":"FAIL",detail:`scenarios=${s.scenarioBaseline?.scenarioCount}; matches=${s.fullMatchCampaign?.matchCount}; deterministic=${s.deterministicReproduction?.matched}; campaign=${s.fullMatchCampaign?.campaignHash}`});}catch(error){checks.push({name:"phase19-simulation",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const p=await json<{verdict?:string;verifiedPairCount?:number;failureCount?:number;runtime?:string;aggregateHash?:string}>(path.join(projectRoot,"reports/independent-python-replay-verification.json"));const ok=p.verdict==="PASS"&&p.verifiedPairCount===121&&p.failureCount===0;checks.push({name:"independent-python-runtime",status:ok?"PASS":"FAIL",detail:`runtime=${p.runtime}; pairs=${p.verifiedPairCount}; failures=${p.failureCount}; aggregate=${p.aggregateHash}`});}catch(error){checks.push({name:"independent-python-runtime",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const c=await json<{verdict?:string;certifiedReplayCount?:number;invariantFuzzCases?:number;publicLeakFailures?:unknown[];invariantFuzzFailures?:unknown[];sourceTestCoverage?:{uniqueSourceIds?:number;missingSourceIds?:string[]};independentRuntime?:{verifiedPairCount?:number}}>(path.join(projectRoot,"reports/final-release-certification.json"));const ok=c.verdict==="PASS"&&c.certifiedReplayCount===121&&(c.invariantFuzzCases??0)>=600&&c.publicLeakFailures?.length===0&&c.invariantFuzzFailures?.length===0&&c.sourceTestCoverage?.uniqueSourceIds===120&&c.sourceTestCoverage.missingSourceIds?.length===0&&c.independentRuntime?.verifiedPairCount===121;checks.push({name:"final-certification",status:ok?"PASS":"FAIL",detail:`replays=${c.certifiedReplayCount}; fuzz=${c.invariantFuzzCases}; source=${c.sourceTestCoverage?.uniqueSourceIds}/120; missing=${c.sourceTestCoverage?.missingSourceIds?.join(",")}`});}catch(error){checks.push({name:"final-certification",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 try{const fixtureFiles=(await readdir(path.join(projectRoot,"fixtures"))).filter(n=>n.endsWith(".json")&&n!=="phase16-rng-vectors.json");let count=0;for(const name of fixtureFiles)count+=(await loadFixtures(path.join(projectRoot,"fixtures",name))).length;checks.push({name:"fixture-count",status:count===121?"PASS":"FAIL",detail:`${count} executable fixtures`});}catch(error){checks.push({name:"fixture-count",status:"FAIL",detail:error instanceof Error?error.message:String(error)});}
 for(const phase of [16,17,18,19,20]){try{const status=await json<{engine_version?:string;completed_phases?:number[];status?:string}>(path.join(projectRoot,"canonical",`IMPLEMENTATION_STATUS_PHASE_${phase}.json`));const ok=status.engine_version===CERTIFIED_BASE_VERSION&&status.completed_phases?.includes(phase)===true&&status.status==="complete";checks.push({name:`phase${phase}-status-record`,status:ok?"PASS":"FAIL",detail:`engine=${status.engine_version}; status=${status.status}; phases=${canonicalize(status.completed_phases)}`});}catch(error){checks.push({name:`phase${phase}-status-record`,status:"FAIL",detail:error instanceof Error?error.message:String(error)});}}
 const files=await walk(projectRoot);const hashes:Record<string,string>={};const generated=new Set(["MANIFEST.json","SHA256SUMS","reports/release-validation.json","reports/release-validation.md"]);for(const rel of files.filter(f=>!generated.has(f)))hashes[rel]=await sha256File(path.join(projectRoot,rel));const payloadHash=createHash("sha256").update(canonicalize(hashes),"utf8").digest("hex");const manifest={manifestVersion:2,package:"@intrilex/headless-engine",version:RULES_AUTHORITY_VERSION,certifiedBaseVersion:CERTIFIED_BASE_VERSION,rulesVersion:"4.1",rulesAuthorityVersion:RULES_AUTHORITY_VERSION,canonStatus:"official",implementedPhases:Array.from({length:19},(_,i)=>i+2),releaseClass:"stable-certified-headless-engine",generatedAt:"2026-07-26T00:00:00-04:00",historicalV410Phase218Aggregate:HISTORICAL_V410_PHASE218_AGGREGATE,preservedPhase218Aggregate:PRESERVED_AGGREGATE,historicalV410ConformanceAggregate:HISTORICAL_V410_AGGREGATE,finalConformanceAggregate:FINAL_AGGREGATE,files:hashes,payloadHash};await writeFile(path.join(projectRoot,"MANIFEST.json"),JSON.stringify(manifest,null,2)+"\n","utf8");await writeFile(path.join(projectRoot,"SHA256SUMS"),Object.entries(hashes).sort(([a],[b])=>a.localeCompare(b)).map(([rel,hash])=>`${hash}  ${rel}`).join("\n")+"\n","utf8");checks.push({name:"manifest-generated",status:"PASS",detail:`${Object.keys(hashes).length} payload files; ${payloadHash}`});
 const verdict=checks.every(c=>c.status==="PASS")?"PASS":"FAIL";const output={verdict,checks} as const;await writeFile(path.join(projectRoot,"reports","release-validation.json"),JSON.stringify(output,null,2)+"\n","utf8");await writeFile(path.join(projectRoot,"reports","release-validation.md"),`# Intrilex v4.1 Final Release Validation\n\n**Verdict: ${verdict}**\n\n| Check | Status | Detail |\n|---|---|---|\n${checks.map(c=>`| ${c.name} | ${c.status} | ${c.detail.replaceAll("|","\\|")} |`).join("\n")}\n`,"utf8");return output;
}
