// ═══════════════════════════════════════════════════════════════
// workspaces/evidence.js — /evidence workspace: integrity and provenance
// ═══════════════════════════════════════════════════════════════

import { state,   app,   esc,   short,   definitionList } from '../state.js?v=659a089d50b6';
import { ENGINE_VERSION, RULES_VERSION } from '../version.js?v=659a089d50b6';

export function renderEvidence() {
  const c = state.capabilities, o = state.observatory, registry = o.metricRegistry ?? {}, anomalies = o.anomalies ?? [];
  const engineTests = c.engineTests ?? { passed: 0, total: 0 };
  const labVersion = c.labVersion ?? state.buildInfo?.version ?? '—';
  const conformanceTotal = c.engine?.conformanceReplayCount ?? 121;
  app.innerHTML = `<div class="grid four"><div class="metric-card"><small>Engine tests</small><div class="metric-value">${engineTests.passed}/${engineTests.total}</div><div class="metric-detail">${engineTests.total ? 'Pass/priority/Quick/Interrupt' : 'Not reported in build'}</div></div><div class="metric-card"><small>Conformance</small><div class="metric-value">${conformanceTotal}</div><div class="metric-detail">Certified replays</div></div><div class="metric-card"><small>Lab version</small><div class="metric-value">${esc(labVersion)}</div></div><div class="metric-card"><small>Engine</small><div class="metric-value">${esc(c.engine?.version ?? ENGINE_VERSION)}</div><div class="metric-detail">Rules ${esc(c.engine?.rulesVersion ?? RULES_VERSION)}</div></div></div>
  <section class="panel" style="margin-top:16px"><div class="panel-header"><div><h2>Metric registry</h2><p>All computed metrics with formula provenance</p></div></div><div class="panel-body">${Object.keys(registry).length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Metric</th><th>Version</th><th>Formula</th><th>Uncertainty</th></tr></thead><tbody>${Object.entries(registry).map(([id, m]) => `<tr><td><b>${esc(id)}</b></td><td>${esc(m.version ?? '—')}</td><td class="mono">${esc(m.formula ?? '—')}</td><td>${esc(m.uncertainty ?? '—')}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state"><strong>No metric registry.</strong> Run a campaign to generate the metric registry.</div>'}</div></section>
  <section class="panel" style="margin-top:16px"><div class="panel-header"><div><h2>Capability manifest</h2><p>Supported profiles and engine authority</p></div></div><div class="panel-body">${c.profiles ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Profile</th><th>Autonomy</th><th>Modules</th></tr></thead><tbody>${c.profiles.map(p => `<tr><td><b>${esc(p.id ?? p.profileId)}</b></td><td><span class="status-badge ${p.autonomy === 'SUPPORTED' ? 'supported' : 'danger'}">${esc(p.autonomy)}</span></td><td>${esc((p.modules ?? []).join(', ') || 'none')}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state"><strong>No capability manifest.</strong></div>'}</div></section>
  ${anomalies.length ? `<section class="panel" style="margin-top:16px"><div class="panel-header"><div><h2>Anomalies</h2><p>${anomalies.length} detected</p></div></div><div class="panel-body"><div class="table-wrap"><table class="data-table"><thead><tr><th>Type</th><th>Detail</th><th>Severity</th></tr></thead><tbody>${anomalies.map(a => `<tr><td>${esc(a.type ?? 'unknown')}</td><td>${esc(a.detail ?? '—')}</td><td><span class="status-badge ${a.severity === 'high' ? 'danger' : 'warning'}">${esc(a.severity ?? 'low')}</span></td></tr>`).join('')}</tbody></table></div></div></section>` : ''}
  <section class="panel" style="margin-top:16px"><div class="panel-header"><div><h2>Release provenance</h2><p>Build information and artifact integrity</p></div></div><div class="panel-body">${definitionList([['Capability hash', short(c.capabilityHash)], ['Observatory hash', short(o.observatoryHash)], ['Campaign hash', short(state.aggregate?.canonicalResultHash)], ['Engine version', c.engine?.version ?? ENGINE_VERSION], ['Rules version', c.engine?.rulesVersion ?? RULES_VERSION], ['Lab version', labVersion]])}</div></section>`;
}
