// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const LAB_VERSION = "0.29.0";
export const ENGINE_VERSION = "4.2.6";
export const RULES_VERSION = "4.3.1";
export const OFFICIAL_RULES_VERSION = "4.3.1";
export const SCHEMA_VERSION = "4.1.0";
export const DECISION_TRACE_SCHEMA_VERSION = "2.0.0";
export const ANALYTICS_SCHEMA_VERSION = "4.2.0";
export const TELEMETRY_SCHEMA_VERSION = "4.1.0";
export const REPLAY_DATA_VERSION = "0.10.1";
