import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync, readFileSync, cpSync, rmSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { hashCanonical } from '@intrilex/shared';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rootPackage = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const productVersion = rootPackage.version;
const dist = path.join(root, 'apps/lab-web/dist');
const vendorRuntime = path.join(root, 'runtime/autonomy-engine-dist/src');

// ── Load .env file (lightweight dotenv — no dependency) ──
const envPath = path.join(root, '.env');
if (existsSync(envPath)) {
  const envContent = readFileSync(envPath, 'utf8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (key && !(key in process.env)) {
      process.env[key] = value;
    }
  }
}
const browserEngine = path.join(dist, 'engine');
const certifiedReplaySource = path.join(root, 'upstream/intrilex-engine-4.2.6-attachment-integrity-hotfix/replays');
const certifiedReplayDist = path.join(dist, 'data/certified-replays');

const capabilities = spawnSync(process.execPath, ['scripts/generate-capability-manifest.mjs'], { cwd: root, stdio: 'inherit' });
if (capabilities.status !== 0) process.exit(capabilities.status ?? 1);

// Generate version module from package.json (single source of truth)
const versionGen = spawnSync(process.execPath, ['scripts/generate-version.mjs'], { cwd: root, stdio: 'inherit' });
if (versionGen.status !== 0) process.exit(versionGen.status ?? 1);
const versionBrowser = spawnSync(process.execPath, ['scripts/generate-version.mjs', '--browser'], { cwd: root, stdio: 'inherit' });
if (versionBrowser.status !== 0) process.exit(versionBrowser.status ?? 1);

const generated = spawnSync(process.execPath, ['scripts/generate-data.mjs'], { cwd: root, stdio: 'inherit' });
if (generated.status !== 0) process.exit(generated.status ?? 1);
if (process.env.INTRILEX_SKIP_AUTONOMY_REPLAY_REGEN !== '1') {
  const autonomyArtifacts = spawnSync(process.execPath, ['scripts/generate-autonomy-replay-artifacts.mjs','--resume'], { cwd: root, stdio: 'inherit' });
  if (autonomyArtifacts.status !== 0) process.exit(autonomyArtifacts.status ?? 1);
}
const observatory = spawnSync(process.execPath, ['scripts/generate-observatory-analytics.mjs'], { cwd: root, stdio: 'inherit' });
if (observatory.status !== 0) process.exit(observatory.status ?? 1);
const extract = spawnSync(process.execPath, ['scripts/extract-analysis.mjs', '--out', 'sample-data/observatory/extract.json'], { cwd: root, stdio: 'inherit' });
if (extract.status !== 0) process.exit(extract.status ?? 1);
const extractMd = spawnSync(process.execPath, ['scripts/extract-analysis.mjs', '--markdown', '--out', 'sample-data/observatory/extract.md'], { cwd: root, stdio: 'inherit' });
if (extractMd.status !== 0) process.exit(extractMd.status ?? 1);

// ── Decision trace index: verify or regenerate (prevents silent broken dist) ──
const traceIndexPath = path.join(root, 'sample-data/autonomy/decision-trace-index.json');
let traceIndexExists = true;
try { await readFile(traceIndexPath, 'utf8'); } catch { traceIndexExists = false; }
if (!traceIndexExists) {
  console.log('decision-trace-index.json missing — regenerating via generate-decision-traces.mjs --resume');
  const traces = spawnSync(process.execPath, ['scripts/generate-decision-traces.mjs', '--resume'], { cwd: root, stdio: 'inherit' });
  if (traces.status !== 0) process.exit(traces.status ?? 1);
}
// ── Card art: regenerate WebP board assets from source PNGs (deterministic, skip-unchanged) ──
const cardArt = spawnSync(process.execPath, ['scripts/build-card-art.mjs'], { cwd: root, stdio: 'inherit' });
if (cardArt.status !== 0) process.exit(cardArt.status ?? 1);

// ── Ranked glyphs: regenerate PNG derivatives from 1024 masters (deterministic, skip-unchanged) ──
// Masters live in <root>/ranked-glyphs/ (canonical immutable source artwork).
// Derivatives (256/128/64, alpha-preserving) ship under apps/lab-web/src/assets/ranked/glyphs/.
const rankedGlyphs = spawnSync(process.execPath, ['scripts/build-ranked-glyphs.mjs'], { cwd: root, stdio: 'inherit' });
if (rankedGlyphs.status !== 0) process.exit(rankedGlyphs.status ?? 1);

// ── Social share image: og-image.png is hand-authored and committed at
// apps/lab-web/src/assets/og-image.png. It is NOT regenerated by the build —
// do not overwrite the committed asset. Copied to dist/ by the recursive
// src→dist copy below, and to neocities-deploy/ by sync-neocities.mjs.

// Use synchronous fs operations for the initial dist creation to avoid
// Windows filesystem sync races where async cp/rm promises resolve before
// the OS has committed the changes, causing spawnSync (bundle.mjs) to fail.
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(path.join(root, 'apps/lab-web/src'), dist, { recursive: true });
// ── Analytics AI core: copy isomorphic package modules into dist/analytics-ai ──
// The browser UI adapters (apps/lab-web/src/analytics-ai/*.js) import these
// .mjs modules via relative paths. The package is self-contained (no workspace
// imports, only the Fetch API), so no import rewriting is required.
{
  const aaiSrc = path.join(root, 'packages/analytics-ai/src');
  const aaiDist = path.join(dist, 'analytics-ai');
  await mkdir(aaiDist, { recursive: true });
  const aaiModules = (await readdir(aaiSrc)).filter(f => f.endsWith('.mjs'));
  for (const mod of aaiModules) {
    await cp(path.join(aaiSrc, mod), path.join(aaiDist, mod));
  }
}
// ── Replay Caster: copy browser-bundleable package modules into dist/replay-caster ──
// The browser UI (apps/lab-web/src/workspaces/caster-workspace.js) imports these
// .mjs modules via the browser-entry.js adapter. The package imports
// @intrilex/shared (aliased to the browser shim by bundle.mjs) and uses
// string-concatenated dynamic imports for Node-only packages (so esbuild
// leaves them as runtime dynamic imports, never bundled for the browser).
{
  const rcSrc = path.join(root, 'packages/replay-caster/src');
  const rcDist = path.join(dist, 'replay-caster');
  await mkdir(rcDist, { recursive: true });
  const rcModules = (await readdir(rcSrc)).filter(f => f.endsWith('.mjs'));
  for (const mod of rcModules) {
    await cp(path.join(rcSrc, mod), path.join(rcDist, mod));
  }
}
// ── Achievements: copy isomorphic package modules into dist/achievements ──
// The browser UI adapters (apps/lab-web/src/achievements/*.js) import these
// .mjs modules via relative paths. The package is self-contained (no workspace
// imports), so no import rewriting is required.
{
  const achSrc = path.join(root, 'packages/achievements/src');
  const achDist = path.join(dist, 'achievements');
  await mkdir(achDist, { recursive: true });
  const achModules = (await readdir(achSrc)).filter(f => f.endsWith('.mjs'));
  for (const mod of achModules) {
    await cp(path.join(achSrc, mod), path.join(achDist, mod));
  }
}
// Copy scoring.mjs with Node→browser import rewrite (replace node:crypto with browser SHA-256 shim)
{
  let scoringSrc = await readFile(path.join(root, 'packages/policies/src/scoring.mjs'), 'utf8');
  scoringSrc = scoringSrc.replace(/import\s+\{\s*createHash\s*\}\s+from\s+["']node:crypto["'];?/g, 'import { sha256Text } from "./engine/hash.js";');
  scoringSrc = scoringSrc.replace(/createHash\(['"]sha256['"]\)\.update\((.+)\)\.digest\(['"]hex['"]\)/g, 'sha256Text($1)');
  await writeFile(path.join(dist, 'policy-scoring.js'), scoringSrc);
}
await cp(path.join(root, 'apps/lab-web/src/decision-intelligence.js'), path.join(dist, 'decision-intelligence.js'));

// ── HYBRIX browser bundle: copy agent modules with import rewriting ──
const hybrixSrc = path.join(root, 'packages/game-ai/src');
const hybrixDist = path.join(dist, 'hybrix');
await mkdir(hybrixDist, { recursive: true });
const hybrixModules = ['agent.mjs','perception.mjs','personality.mjs','memory.mjs','cognition.mjs','coordination.mjs','failsafe.mjs','debug.mjs','difficulty.mjs','config.mjs','policy-adapter.mjs','rank-strategy.mjs'];
for (const mod of hybrixModules) {
  let src = await readFile(path.join(hybrixSrc, mod), 'utf8');
  // Rewrite package imports to browser-compatible paths
  src = src.replace(/from\s+["']@intrilex\/shared["']/g, 'from "./browser-shared.js"');
  src = src.replace(/from\s+["']@intrilex\/policy-sdk["']/g, 'from "./browser-policy-sdk.js"');
  src = src.replace(/from\s+["']@intrilex\/policies\/scoring["']/g, 'from "../policy-scoring.js"');
  // Rewrite .mjs to .js in relative imports
  src = src.replace(/from\s+["']\.\/([\w-]+)\.mjs["']/g, 'from "./$1.js"');
  const outName = mod.replace(/\.mjs$/, '.js');
  await writeFile(path.join(hybrixDist, outName), src);
}
// Create browser-shared.js — re-exports hashCanonical from engine
await writeFile(path.join(hybrixDist, 'browser-shared.js'), [
  "export { hashCanonical, sha256Text } from '../engine/hash.js';",
  "export { canonicalize, canonicalClone } from '../engine/canonical-json.js';",
  "export function sanitizeCsvCell(value) {",
  "  const text = value == null ? '' : String(value);",
  "  const safe = /^[=+\\-@]/.test(text) ? `'${text}` : text;",
  "  return /[\",\\n\\r]/.test(safe) ? `\"${safe.replaceAll('\"', '\"\"')}\"` : safe;",
  "}",
  ''
].join('\n'));
// Create browser-policy-sdk.js — DeterministicPolicyRng (no Node.js deps)
await writeFile(path.join(hybrixDist, 'browser-policy-sdk.js'), [
  "import { hashCanonical } from './browser-shared.js';",
  "export class DeterministicPolicyRng {",
  "  constructor(seed) { const value = Number(seed) >>> 0; this.seed = value || 1; this.cursor = 0; }",
  "  nextUint32() { let x = this.seed >>> 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; this.seed = x >>> 0; this.cursor += 1; return this.seed; }",
  "  nextIndex(length) { if (!Number.isInteger(length) || length <= 0) throw new RangeError('length'); return this.nextUint32() % length; }",
  "}",
  "export function createPolicyDefinition({ policyId, version, traits, choose }) {",
  "  return { policyId, version: version ?? '1.0.0', traits: traits ?? {}, choose, policyHash: hashCanonical({ policyId, version: version ?? '1.0.0', traits: traits ?? {} }) };",
  "}",
  ''
].join('\n'));
// Copy sample-data into dist/data — exclude heavy replay blob directories by default.
// The browser lazy-loads individual replay JSONs by fixture ID, so the blobs are not
// needed at boot. Set INTRILEX_INCLUDE_REPLAY_BLOBS=1 to include them (for local dev
// or offline static hosting where no separate data CDN is used).
const includeReplayBlobs = process.env.INTRILEX_INCLUDE_REPLAY_BLOBS === '1';
const replayBlobDirs = new Set([
  'autonomy/lab-replays/authorized',
  'autonomy/lab-replays/public',
  'autonomy/replays/authorized',
  'autonomy/replays/public',
  'autonomy/decision-traces',
  // data/replays/public/ is redundant with data/certified-replays/ — the browser
  // app loads certified replays via data/certified-replays/<id>.certified.replay.json,
  // never data/replays/public/<id>.json. Excluding saves ~1MB per deploy.
  'replays/public',
]);
// Individual autonomy JSON files not fetched by the browser app. These are campaign
// accounting/retention artifacts used by server-side analysis and tests (which read
// from sample-data/, not dist/). Excluding saves ~36MB per deploy.
const excludedDataFiles = new Set([
  'autonomy/campaign-accounting.json',
  'autonomy/retention-index.json',
  'autonomy/execution-manifests.json',
  'autonomy/experiment.json',
  // The browser loads match-summaries.ndjson (line 97 of data-loader.js), not .csv
  'autonomy/match-summaries.csv',
]);
if (includeReplayBlobs) {
  await cp(path.join(root, 'sample-data'), path.join(dist, 'data'), { recursive: true });
} else {
  await cp(path.join(root, 'sample-data'), path.join(dist, 'data'), {
    recursive: true,
    filter: (src) => {
      const rel = path.relative(path.join(root, 'sample-data'), src);
      // Always copy root and top-level entries; skip blob dirs and excluded files
      if (!rel || rel === '.') return true;
      const relFwd = rel.replace(/\\/g, '/');
      return !replayBlobDirs.has(relFwd) && !excludedDataFiles.has(relFwd);
    },
  });
  console.log(`build: excluded replay blob directories and unused data files (set INTRILEX_INCLUDE_REPLAY_BLOBS=1 to include) — saved ~670MB`);
}
// On Windows external/mapped drives, cp with filter may create directory entries
// without fully writing file contents. Re-copy the observatory directory without
// a filter to ensure the ~37MB analytics.json is fully written.
const observatorySrcDir = path.join(root, 'sample-data', 'observatory');
const observatoryDistDir = path.join(dist, 'data', 'observatory');
await rm(observatoryDistDir, { recursive: true, force: true });
// Retry cp on Windows — antivirus/indexer can briefly lock source files
let cpSuccess = false;
for (let attempt = 0; attempt < 3; attempt++) {
  try {
    await cp(observatorySrcDir, observatoryDistDir, { recursive: true });
    cpSuccess = true;
    break;
  } catch (err) {
    if (attempt < 2) {
      await new Promise(r => setTimeout(r, 500));
      await rm(observatoryDistDir, { recursive: true, force: true });
      continue;
    }
    throw err;
  }
}
if (!cpSuccess) throw new Error('Failed to copy observatory directory after 3 retries');
// Wait for filesystem sync and verify the critical file is actually readable
// (not just present — on Windows, stat may report size > 0 before content is flushed)
let observatoryReady = false;
for (let attempt = 0; attempt < 30; attempt++) {
  try {
    const data = await readFile(path.join(observatoryDistDir, 'analytics.json'), 'utf8');
    if (data.length > 0) { observatoryReady = true; break; }
  } catch { /* not ready yet — content not flushed */ }
  await new Promise(r => setTimeout(r, 500));
}
if (!observatoryReady) {
  throw new Error('Observatory analytics.json could not be read and verified after 30 retries');
}

// ── Slim index files for browser deploy ──────────────────────────────────
// The replay-index.json and lab-replay-index.json each embed a ~180KB `summary`
// object per autonomy record (100 records × 180KB ≈ 18MB per file). The browser
// app never reads `record.summary` — it loads match summaries separately from
// match-summaries.ndjson. Stripping `summary` from the dist copies saves ~36MB.
// Tests verify `record.summary` from sample-data/ (the source), not dist/.
async function slimIndexFile(filePath, label) {
  const abs = path.join(dist, 'data', filePath);
  if (!existsSync(abs)) { console.log(`build: skipped slimming ${label} — file not present`); return; }
  let raw;
  try {
    raw = JSON.parse(await readFile(abs, 'utf8'));
  } catch { console.log(`build: skipped slimming ${label} — unreadable`); return; }
  if (!raw.records) return;
  let stripped = 0;
  raw.records = raw.records.map((r) => {
    if (r.summary) { stripped++; const rest = { ...r }; delete rest.summary; return rest; }
    return r;
  });
  // Recompute indexHash over the slimmed core (without the hash field itself)
  const core = { ...raw };
  delete core.indexHash;
  raw.indexHash = hashCanonical(core);
  try {
    await writeFile(abs, JSON.stringify(raw) + '\n');
    console.log(`build: slimmed ${label} — stripped ${stripped} record summaries, ${label} is now ${JSON.stringify(raw).length} bytes`);
  } catch (e) {
    console.log(`build: could not write slimmed ${label} — ${e.code}`);
  }
}
await slimIndexFile('replay-index.json', 'replay-index.json');
await slimIndexFile('autonomy/lab-replay-index.json', 'lab-replay-index.json');

// ── Clean up empty directories left by blob-dir exclusion filter ──────────
// The cp filter creates parent directories before excluding their children,
// leaving empty dirs like data/autonomy/replays/ and data/autonomy/lab-replays/.
for (const emptyDir of ['data/autonomy/replays', 'data/autonomy/lab-replays', 'data/replays/public']) {
  const abs = path.join(dist, emptyDir);
  if (existsSync(abs)) await rm(abs, { recursive: true, force: true });
}

await mkdir(path.join(dist, 'data/release'), { recursive: true });
await cp(path.join(root, 'docs/INTRILEX_v4.3.1_COMPLETE_PLAYER_RULEBOOK.md'), path.join(dist, 'data/rulebook.md'));
await cp(path.join(root, 'CHANGELOG.md'), path.join(dist, 'data/changelog.md'));
await cp(path.join(root, 'reports/capability-manifest.json'), path.join(dist, 'data/release/capability-manifest.json'));

const importPattern = /from\s+["']\.\/(.+?\.js)["']/g;
const requiredModules = new Set();
async function collect(moduleName) {
  if (requiredModules.has(moduleName)) return;
  requiredModules.add(moduleName);
  const source = await readFile(path.join(vendorRuntime, moduleName), 'utf8');
  for (const match of source.matchAll(importPattern)) await collect(match[1]);
}
for (const entry of ['phase16.js', 'engine.js', 'views.js', 'autonomy.js', 'core-autonomy.js', 'core-authority.js', 'core-effects.js', 'core-response.js', 'core-private-choice.js', 'core-advanced.js']) await collect(entry);
requiredModules.delete('hash.js');
await mkdir(browserEngine, { recursive: true });
for (const moduleName of [...requiredModules].sort()) {
  await cp(path.join(vendorRuntime, moduleName), path.join(browserEngine, moduleName));
}
await cp(path.join(root, 'packages/browser-crypto-shim/src/hash.js'), path.join(browserEngine, 'hash.js'));
await writeFile(path.join(browserEngine, 'browser-entry.js'), [
  "export { IntrilexEngine } from './engine.js';",
  "export { parseCertifiedReplay, verifyCertifiedReplay, createCertifiedReplay, publicCertifiedReplayView, serializeCertifiedReplay } from './phase16.js';",
  "export { publicStateView, privateStateView, publicEventView } from './views.js';",
  "export { hashCanonical, sha256Text } from './hash.js';",
  "export { deriveSecuredPoints } from './state.js';",
  "export { FIRST_CONTACT_AUTONOMY_BASELINE_PROFILE, FIRST_CONTACT_AUTONOMY_ESSENTIALS_PROFILE, FIRST_CONTACT_RESPONSE_AUTHORITY_PROFILE, FIRST_CONTACT_PRIVATE_CHOICE_AUTHORITY_PROFILE, FIRST_CONTACT_TRIGGER_CLOSURE_PROFILE, createMatchState, enumerateLegalActions, authorizedLegalActionView, advanceToDecision, autonomousCapabilities, runRandomLegalMatch } from './autonomy.js';",
  "export { createCoreMatchState, advanceCoreToDecision, enumerateCoreLegalActions, enumerateCoreResponseActions, enumerateCorePrivateChoiceActions, toAuthorizedCoreAction, coreAuthorityCapabilities } from './core-autonomy.js';",
  "export { CORE_FOUNDATION_AUTHORITY_PROFILE } from './core-authority.js';",
  "export { CORE_EFFECT_DECLARATION_PROFILE } from './core-effects.js';",
  "export { CORE_RESPONSE_AUTHORITY_PROFILE } from './core-response.js';",
  "export { CORE_PRIVATE_CHOICE_AUTHORITY_PROFILE } from './core-private-choice.js';",
  "export { CORE_ADVANCED_AUTHORITY_PROFILE, CORE_UNRESTRICTED_AUTHORITY_PROFILE } from './core-advanced.js';",
  ''
].join('\n'));

// ── Browser-safe @intrilex/shared shim ─────────────────────────────────
// packages/shared/src/canonical.mjs imports `node:crypto`, which esbuild
// cannot resolve when bundling for the browser platform. Several browser
// modules (e.g. @intrilex/decision-intelligence/* imported by profile.js
// and ranked-duel-terminal.mjs) transitively import @intrilex/shared.
// This shim re-exports the browser crypto shim's hash primitives and
// defines the pure helpers (sanitizeCsvCell, stableSortBy) so the browser
// bundle never reaches node:crypto. bundle.mjs aliases @intrilex/shared
// to this file.
await writeFile(path.join(dist, 'shared-browser.js'), [
  "// shared-browser.js — Browser-safe replacement for @intrilex/shared canonical.mjs.",
  "// Re-exports hash primitives from the browser crypto shim and defines pure",
  "// helpers so the browser bundle never pulls in node:crypto.",
  "export { canonicalize, canonicalClone } from './engine/canonical-json.js';",
  "export { sha256Text, hashCanonical } from './engine/hash.js';",
  "export function sanitizeCsvCell(value) {",
  "  const text = value == null ? '' : String(value);",
  "  const safe = /^[=+\\-@]/.test(text) ? `'${text}` : text;",
  "  return /[\",\\n\\r]/.test(safe) ? `\"${safe.replaceAll('\"', '\"\"')}\"` : safe;",
  "}",
  "export function stableSortBy(items, selector) {",
  "  return [...items].sort((a, b) => String(selector(a)).localeCompare(String(selector(b))));",
  "}",
  ''
].join('\n'));

await mkdir(certifiedReplayDist, { recursive: true });
const certifiedReplayFiles = (await readdir(certifiedReplaySource))
  .filter((name) => name.endsWith('.certified.replay.json') && !name.includes('.public.certified.'))
  .sort();
for (const name of certifiedReplayFiles) {
  await cp(path.join(certifiedReplaySource, name), path.join(certifiedReplayDist, name));
}

// Count autonomy (Advanced Core) replays for the total certified replay count
let autonomyReplayCount = 0;
try {
  const autonomyIndex = JSON.parse(await readFile(path.join(root, 'sample-data/autonomy/lab-replay-index.json'), 'utf8'));
  autonomyReplayCount = autonomyIndex.records?.length ?? 0;
} catch { /* autonomy index may not exist */ }
const totalCertifiedReplayCount = certifiedReplayFiles.length + autonomyReplayCount;

await writeFile(path.join(dist, 'BUILD_INFO.json'), JSON.stringify({
  version: productVersion,
  engineVersion: '4.2.6',
  rulesVersion: '4.3.1',
  buildKind: 'UNRESTRICTED_CORE_PLAYER_RELEASE',
  browserEngineModules: [...requiredModules, 'hash.js', 'browser-entry.js'].sort(),
  certifiedReplayCount: totalCertifiedReplayCount,
  cardFaceRendererVersion: '1.1.0',
  cardFaceExactCardCount: 54,
  cardFaceCanonicalCardCount: 54
}, null, 2) + '\n');

// Generate browser-safe canonical rank authority artifact
const { pathToFileURL } = await import('node:url');
const { canonicalRankAuthority } = await import(pathToFileURL(path.join(root, 'packages/engine-adapter/src/adapter.mjs')).href);
const rankAuthority = canonicalRankAuthority();
const rankAuthorityDir = path.join(dist, 'data', 'release');
await mkdir(rankAuthorityDir, { recursive: true });
await writeFile(path.join(rankAuthorityDir, 'rank-authority.json'), JSON.stringify(rankAuthority, null, 2) + '\n');

// ── Rank Power data liveness assertion (prevents silent /ranks data loss) ──
const observatoryAnalyticsPath = path.join(dist, 'data', 'observatory', 'analytics.json');
// Diagnostic: check if the file exists before attempting to read it
if (!existsSync(observatoryAnalyticsPath)) {
  console.error(`build: WARNING — analytics.json missing before rank power assertion, re-copying observatory...`);
  // Re-copy the observatory directory as a workaround
  await rm(path.join(dist, 'data', 'observatory'), { recursive: true, force: true });
  await cp(observatorySrcDir, path.join(dist, 'data', 'observatory'), { recursive: true });
  // Wait for flush
  await new Promise(r => setTimeout(r, 1000));
}
let rankPowerAssertion = null;
try {
  // Retry reads for up to ~5s — on Windows external/mapped drives, large files
  // (analytics.json is ~37MB) may not be readable immediately after cp completes.
  let observatoryRaw = null;
  let lastErr = null;
  for (let attempt = 0; attempt < 20; attempt++) {
    try { observatoryRaw = await readFile(observatoryAnalyticsPath, 'utf8'); break; } catch (e) { lastErr = e; if (attempt === 0) console.error(`build: analytics.json read retry — ${e.code ?? e.message}`); await new Promise(r => setTimeout(r, 500)); }
  }
  if (!observatoryRaw) throw new Error(`Unable to read ${observatoryAnalyticsPath} after 20 retries (filesystem sync race) — last error: ${lastErr?.code ?? lastErr?.message}`);
  const observatoryJson = JSON.parse(observatoryRaw);
  const rankCount = observatoryJson.rankPower?.ranks ? Object.keys(observatoryJson.rankPower.ranks).length : 0;
  const ladderLength = observatoryJson.rankPower?.ladder?.length ?? 0;
  if (rankCount < 18) {
    throw new Error(`rankPower.ranks has ${rankCount} entries, expected 18. Rank Power Observatory data is incomplete.`);
  }
  if (ladderLength < 18) {
    throw new Error(`rankPower.ladder has ${ladderLength} entries, expected 18.`);
  }
  rankPowerAssertion = `${rankCount} ranks, ladder ${ladderLength} entries`;
  // Assert variant analytics is present (v0.16.0 Rank Anatomy)
  if (!observatoryJson.variantAnalytics) {
    throw new Error('Observatory analytics.json missing variantAnalytics. Rank Anatomy Observatory data is required for v0.16.0.');
  }
} catch (err) {
  if (err.message.includes('rankPower') || err.message.includes('variantAnalytics')) throw err;
  throw new Error(`Observatory analytics.json missing or unreadable for rank power assertion: ${err.message}`);
}

// Assert Rank Anatomy registry artifact exists
const rankAnatomyRegistryPath = path.join(dist, 'data', 'observatory', 'rank-anatomy-registry.json');
try {
  let registryRaw = null;
  for (let attempt = 0; attempt < 10; attempt++) {
    try { registryRaw = await readFile(rankAnatomyRegistryPath, 'utf8'); break; } catch { await new Promise(r => setTimeout(r, 500)); }
  }
  if (!registryRaw) throw new Error(`Unable to read ${rankAnatomyRegistryPath} after 10 retries (filesystem sync race)`);
  const registryJson = JSON.parse(registryRaw);
  if (registryJson.rankCount !== 15) throw new Error(`rank-anatomy-registry.json has ${registryJson.rankCount} ranks, expected 15.`);
  if (registryJson.spadesVariantCount !== 13) throw new Error(`rank-anatomy-registry.json has ${registryJson.spadesVariantCount} Spades variants, expected 13.`);
  if (registryJson.superEffectCount !== 9) throw new Error(`rank-anatomy-registry.json has ${registryJson.superEffectCount} Super effects, expected 9.`);
} catch (err) {
  throw new Error(`Rank Anatomy registry assertion failed: ${err.message}`);
}

console.log(`BUILD PASS: ${dist}; browserModules=${requiredModules.size + 2}; certifiedReplays=${certifiedReplayFiles.length}; rankPower=[${rankPowerAssertion}]`);

// Windows filesystem sync race: async fs operations (cp, writeFile) may not
// have flushed to disk before the child process starts. Verify ALL critical
// files exist before invoking bundle.mjs. If any are missing, re-copy
// SYNCHRONOUSLY (cpSync) to guarantee the files are on disk before spawnSync.
const criticalFiles = [
  'app.js',
  'styles.css',
  'shared-browser.js',
  'engine/browser-entry.js',
  'engine/hash.js',
  'engine/ranks.js',
  'engine/canonical-json.js',
  'play/achievements/achievement-ui.js',
  'policy-scoring.js',
  'hybrix/policy-adapter.js',
  'analytics-ai/browser-controller.js',
  'analytics-ai/config.mjs',
  'analytics-ai/ollama-client.mjs',
  'analytics-ai/model-discovery.mjs',
  'analytics-ai/deterministic-statistics.mjs',
  'analytics-ai/analysis-controller.mjs',
  'analytics-ai/analysis-cache.mjs',
  'achievements/index.mjs',
];
let missingFiles = criticalFiles.filter(f => !existsSync(path.join(dist, f)));
if (missingFiles.length > 0) {
  console.error(`build: ${missingFiles.length} critical files missing — re-copying synchronously...`);
  // Re-copy src synchronously (includes app.js, play/, achievements/, etc.)
  cpSync(path.join(root, 'apps/lab-web/src'), dist, { recursive: true, force: true });
  // Re-copy analytics-ai modules synchronously
  const aaiSrcDir = path.join(root, 'packages/analytics-ai/src');
  const aaiDistDir = path.join(dist, 'analytics-ai');
  if (existsSync(aaiSrcDir)) {
    cpSync(aaiSrcDir, aaiDistDir, { recursive: true, force: true });
  }
  // Re-copy achievements modules synchronously (from packages/achievements/src)
  const achSrcDir = path.join(root, 'packages/achievements/src');
  const achDistDir = path.join(dist, 'achievements');
  if (existsSync(achSrcDir)) {
    cpSync(achSrcDir, achDistDir, { recursive: true, force: true });
  }
  // Re-copy engine files synchronously
  cpSync(path.join(root, 'packages/browser-crypto-shim/src/hash.js'), path.join(dist, 'engine/hash.js'), { force: true });
  // Re-write shared-browser.js and browser-entry.js synchronously
  const { writeFileSync } = await import('node:fs');
  writeFileSync(path.join(dist, 'shared-browser.js'), [
    "// shared-browser.js — Browser-safe replacement for @intrilex/shared canonical.mjs.",
    "export { canonicalize, canonicalClone } from './engine/canonical-json.js';",
    "export { sha256Text, hashCanonical } from './engine/hash.js';",
    "export function sanitizeCsvCell(value) {",
    "  const text = value == null ? '' : String(value);",
    "  const safe = /^[=+\\-@]/.test(text) ? `'${text}` : text;",
    "  return /[\",\\n\\r]/.test(safe) ? `\"${safe.replaceAll('\"', '\"\"')}\"` : safe;",
    "}",
    "export function stableSortBy(items, selector) {",
    "  return [...items].sort((a, b) => String(selector(a)).localeCompare(String(selector(b))));",
    "}",
    '',
  ].join('\n'));
  // Verify the re-copy worked
  const stillMissing = criticalFiles.filter(f => !existsSync(path.join(dist, f)));
  if (stillMissing.length > 0) {
    console.error(`build: WARNING — ${stillMissing.length} files still missing after re-copy: ${stillMissing.join(', ')}`);
  }
}

// ── Bundle and minify JS/CSS with esbuild (hashed, cache-friendly) ──
const bundleResult = spawnSync(process.execPath, ['scripts/bundle.mjs'], { cwd: root, stdio: 'inherit' });
if (bundleResult.status !== 0) process.exit(bundleResult.status ?? 1);

// ── Rewrite bare @intrilex/account-domain/* imports in raw dist files ────
// esbuild bundles app.js and all its imports into app.[hash].js + chunks.
// However, the raw source files remain in dist (copied from src) and are
// used by tests that import from dist/. These raw files contain bare
// @intrilex/account-domain/* specifiers that browsers cannot resolve. If a
// stale service worker serves these raw files instead of the hashed bundle,
// the browser fails with "Failed to resolve module specifier" errors.
//
// Fix: copy the account-domain package modules into dist/account-domain/
// and rewrite the bare imports to relative paths. This makes the raw files
// browser-safe (no bare specifiers) while keeping them functional for tests.
{
  const accountDomainSrc = path.join(root, 'packages/account-domain/src');
  const accountDomainDist = path.join(dist, 'account-domain');
  await mkdir(accountDomainDist, { recursive: true });
  const accountModules = (await readdir(accountDomainSrc)).filter(f => f.endsWith('.mjs'));
  for (const mod of accountModules) {
    await cp(path.join(accountDomainSrc, mod), path.join(accountDomainDist, mod));
  }

  // Map of bare import specifiers → account-domain module filenames
  // (mirrors packages/account-domain/package.json exports)
  const accountDomainExports = {
    '@intrilex/account-domain/rank-tier': 'rank-tier.mjs',
    '@intrilex/account-domain/leaderboard': 'leaderboard.mjs',
    '@intrilex/account-domain/directory': 'directory.mjs',
    '@intrilex/account-domain/recent-opponents': 'recent-opponents.mjs',
    '@intrilex/account-domain/relationships': 'relationships.mjs',
    '@intrilex/account-domain/profile-domain': 'profile-domain.mjs',
    '@intrilex/account-domain/rating': 'rating.mjs',
    '@intrilex/account-domain/glicko2': 'glicko2.mjs',
    '@intrilex/account-domain/seasons': 'seasons.mjs',
    '@intrilex/account-domain/identity': 'identity.mjs',
    '@intrilex/account-domain/capabilities': 'capabilities.mjs',
    '@intrilex/account-domain/validation': 'validation.mjs',
    '@intrilex/account-domain/tournament-domain': 'tournament-domain.mjs',
    '@intrilex/account-domain/strategic-fingerprint': 'strategic-fingerprint.mjs',
    '@intrilex/account-domain/meta-report': 'meta-report.mjs',
    '@intrilex/account-domain/replay-branching': 'replay-branching.mjs',
    '@intrilex/account-domain/match-stats-aggregator': 'match-stats-aggregator.mjs',
    '@intrilex/account-domain/ranked-entry-requirements': 'ranked-entry-requirements.mjs',
    '@intrilex/account-domain/season-countdown': 'season-countdown.mjs',
  };

  // Recursively find and rewrite .js and .mjs files in dist that contain
  // bare @intrilex/account-domain/* imports.
  let rewrittenCount = 0;
  async function rewriteBareImports(dir) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip directories that don't need rewriting
        if (entry.name === 'engine' || entry.name === 'data' || entry.name === 'assets' ||
            entry.name === 'hybrix' || entry.name === 'achievements' || entry.name === 'analytics-ai' ||
            entry.name === 'account-domain') continue;
        await rewriteBareImports(fullPath);
      } else if (entry.isFile() && (entry.name.endsWith('.js') || entry.name.endsWith('.mjs'))) {
        let content = await readFile(fullPath, 'utf8');
        let modified = false;
        const fileDir = path.dirname(fullPath);
        const relBase = path.relative(fileDir, accountDomainDist).replace(/\\/g, '/');
        for (const [specifier, moduleFile] of Object.entries(accountDomainExports)) {
          const importRegex = new RegExp(
            `from\\s+["']${specifier.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}["']`,
            'g'
          );
          if (importRegex.test(content)) {
            content = content.replace(importRegex, `from "${relBase}/${moduleFile}"`);
            modified = true;
          }
        }
        // Also handle the bare package import (no subpath): @intrilex/account-domain
        const bareImportRegex = /from\s+["']@intrilex\/account-domain["']/g;
        if (bareImportRegex.test(content)) {
          content = content.replace(bareImportRegex, `from "${relBase}/index.mjs"`);
          modified = true;
        }
        if (modified) {
          await writeFile(fullPath, content);
          rewrittenCount++;
        }
      }
    }
  }
  await rewriteBareImports(dist);
  if (rewrittenCount > 0) console.log(`build: rewrote bare @intrilex/account-domain/* imports in ${rewrittenCount} raw dist file(s) → ./account-domain/*.mjs`);
}

// ── Rewrite bare @intrilex/decision-intelligence/* imports in raw dist files ──
// Same defense-in-depth pattern as @intrilex/account-domain above. The
// decision-intelligence package modules are copied into dist/decision-intelligence/
// and bare imports are rewritten to relative paths.
{
  const diSrc = path.join(root, 'packages/decision-intelligence/src');
  const diDist = path.join(dist, 'decision-intelligence');
  await mkdir(diDist, { recursive: true });
  const diModules = (await readdir(diSrc)).filter(f => f.endsWith('.mjs'));
  for (const mod of diModules) {
    await cp(path.join(diSrc, mod), path.join(diDist, mod));
  }

  // Map of bare import specifiers → decision-intelligence module filenames
  // (mirrors packages/decision-intelligence/package.json exports)
  const diExports = {
    '@intrilex/decision-intelligence/decision-trace': 'decision-trace.mjs',
    '@intrilex/decision-intelligence/reason-codes': 'reason-codes.mjs',
    '@intrilex/decision-intelligence/mechanic-registry': 'mechanic-registry.mjs',
    '@intrilex/decision-intelligence/counterfactual': 'counterfactual.mjs',
    '@intrilex/decision-intelligence/anchor': 'anchor.mjs',
    '@intrilex/decision-intelligence/policy-diagnostics': 'policy-diagnostics.mjs',
    '@intrilex/decision-intelligence/teaching-moments': 'teaching-moments.mjs',
    '@intrilex/decision-intelligence/mastery-tracks': 'mastery-tracks.mjs',
    '@intrilex/decision-intelligence/replay-lesson': 'replay-lesson.mjs',
  };

  // The decision-intelligence modules themselves import @intrilex/shared
  // (hashCanonical). In the browser bundle this is aliased to shared-browser.js
  // by bundle.mjs. For the raw dist copies, rewrite @intrilex/shared to the
  // shared-browser.js shim at the dist root.
  const sharedBrowserPath = path.join(dist, 'shared-browser.js');

  let diRewrittenCount = 0;
  async function rewriteDiBareImports(dir) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip directories that don't need rewriting
        if (entry.name === 'engine' || entry.name === 'data' || entry.name === 'assets' ||
            entry.name === 'hybrix' || entry.name === 'achievements' || entry.name === 'analytics-ai' ||
            entry.name === 'account-domain' || entry.name === 'decision-intelligence' ||
            entry.name === 'vendor') continue;
        await rewriteDiBareImports(fullPath);
      } else if (entry.isFile() && (entry.name.endsWith('.js') || entry.name.endsWith('.mjs'))) {
        let content = await readFile(fullPath, 'utf8');
        let modified = false;
        const fileDir = path.dirname(fullPath);
        const relBase = path.relative(fileDir, diDist).replace(/\\/g, '/');
        for (const [specifier, moduleFile] of Object.entries(diExports)) {
          const importRegex = new RegExp(
            `from\\s+["']${specifier.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}["']`,
            'g'
          );
          if (importRegex.test(content)) {
            content = content.replace(importRegex, `from "${relBase}/${moduleFile}"`);
            modified = true;
          }
        }
        // Also handle the bare package import (no subpath)
        const bareImportRegex = /from\s+["']@intrilex\/decision-intelligence["']/g;
        if (bareImportRegex.test(content)) {
          content = content.replace(bareImportRegex, `from "${relBase}/index.mjs"`);
          modified = true;
        }
        if (modified) {
          await writeFile(fullPath, content);
          diRewrittenCount++;
        }
      }
    }
  }
  await rewriteDiBareImports(dist);

  // Rewrite @intrilex/shared imports inside the copied decision-intelligence
  // modules themselves (they import hashCanonical from @intrilex/shared).
  // Point them to the shared-browser.js shim at the dist root.
  const sharedRelBase = path.relative(diDist, dist).replace(/\\/g, '/');
  let diSharedRewritten = 0;
  for (const mod of diModules) {
    const modPath = path.join(diDist, mod);
    let content = await readFile(modPath, 'utf8');
    const sharedRegex = /from\s+["']@intrilex\/shared["']/g;
    if (sharedRegex.test(content)) {
      content = content.replace(sharedRegex, `from "${sharedRelBase}/shared-browser.js"`);
      await writeFile(modPath, content);
      diSharedRewritten++;
    }
  }

  if (diRewrittenCount > 0) console.log(`build: rewrote bare @intrilex/decision-intelligence/* imports in ${diRewrittenCount} raw dist file(s) → ./decision-intelligence/*.mjs`);
  if (diSharedRewritten > 0) console.log(`build: rewrote @intrilex/shared imports in ${diSharedRewritten} decision-intelligence module(s) → shared-browser.js`);
}

// ── Rewrite bare @supabase/supabase-js imports in raw dist files ────────
// Same defense-in-depth pattern as @intrilex/account-domain above.
// esbuild bundles supabase into chunks for the main app, but raw dist files
// (e.g. play/network/supabase-client.js) still have the bare import. If a
// stale service worker serves these raw files, the browser fails with
// "Failed to resolve module specifier" errors.
//
// Fix: use esbuild to create a proper standalone ESM bundle of
// @supabase/supabase-js that exports createClient, write it to
// dist/vendor/supabase-js.js, then rewrite bare imports to point to it.
{
  const vendorDir = path.join(dist, 'vendor');
  await mkdir(vendorDir, { recursive: true });
  const supabaseBundlePath = path.join(vendorDir, 'supabase-js.js');

  // Use esbuild to bundle @supabase/supabase-js into a standalone ESM module
  // that exports createClient. This is the same library esbuild bundles into
  // the app chunks, but as a standalone file with proper export names.
  const supabaseEntry = path.join(vendorDir, '_supabase-entry.js');
  await writeFile(supabaseEntry, 'export { createClient } from "@supabase/supabase-js";\n');

  const esbuildResult = spawnSync(process.execPath, [
    'node_modules/esbuild/bin/esbuild',
    supabaseEntry,
    '--bundle',
    '--format=esm',
    '--outfile=' + supabaseBundlePath,
    '--minify',
    '--target=es2020',
    '--platform=browser',
  ], { cwd: root, stdio: 'pipe', encoding: 'utf8' });

  // Clean up the temporary entry file
  await rm(supabaseEntry, { force: true });

  if (esbuildResult.status !== 0) {
    console.error('build: WARNING — esbuild failed to create supabase standalone bundle');
    console.error(esbuildResult.stderr);
    // Fallback: write a stub that exports a no-op createClient
    await writeFile(supabaseBundlePath, [
      '// Browser-safe supabase-js stub (esbuild fallback)',
      'export function createClient() {',
      '  console.warn("[supabase] Stub createClient called — bundled chunk not loaded.");',
      '  return null;',
      '}',
      ''
    ].join('\n'));
  }

  // Rewrite bare @supabase/supabase-js imports in raw dist files to point
  // to the standalone vendor bundle. Matches both spaced (`from '...'`) and
  // minified (`from"..."`) forms, and both static and dynamic imports.
  const BARE_SUPABASE_PATTERNS = [
    // static:  from '@supabase/supabase-js'   /   from"@supabase/supabase-js"
    /from\s*(["'])@supabase\/supabase-js\1/g,
    // bare side-effect: import '@supabase/supabase-js'
    /import\s*(["'])@supabase\/supabase-js\1/g,
    // dynamic: import('@supabase/supabase-js')
    /import\(\s*(["'])@supabase\/supabase-js\1\s*\)/g,
  ];

  let supabaseRewrittenCount = 0;
  async function rewriteSupabaseImports(dir) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'engine' || entry.name === 'data' || entry.name === 'assets' ||
            entry.name === 'hybrix' || entry.name === 'achievements' || entry.name === 'analytics-ai' ||
            entry.name === 'account-domain' || entry.name === 'vendor' ||
            entry.name === '.split-tmp') continue;
        await rewriteSupabaseImports(fullPath);
      } else if (entry.isFile() && (entry.name.endsWith('.js') || entry.name.endsWith('.mjs'))) {
        let content = await readFile(fullPath, 'utf8');
        const fileDir = path.dirname(fullPath);
        const relBase = path.relative(fileDir, vendorDir).replace(/\\/g, '/');
        const target = `${relBase}/supabase-js.js`;
        let modified = false;
        for (const pattern of BARE_SUPABASE_PATTERNS) {
          if (!pattern.test(content)) continue;
          pattern.lastIndex = 0;
          content = content.replace(pattern, (match) => {
            if (match.startsWith('import(')) return `import("${target}")`;
            if (match.startsWith('import')) return `import "${target}"`;
            return `from "${target}"`;
          });
          modified = true;
        }
        if (modified) {
          await writeFile(fullPath, content);
          supabaseRewrittenCount++;
        }
      }
    }
  }

  await rewriteSupabaseImports(dist);
  if (supabaseRewrittenCount > 0) console.log(`build: rewrote bare @supabase/supabase-js imports in ${supabaseRewrittenCount} raw dist file(s) → ./vendor/supabase-js.js`);

  // ── Fail-closed gate: no browser-served module may contain a bare
  // '@supabase/supabase-js' import statement. String literals (e.g.
  // Symbol.for("@supabase/supabase-js.traceContextExtractor")) and JSDoc
  // comments are fine — only executable import statements are rejected.
  {
    const offenders = [];
    async function auditBareImports(dir) {
      const entries = await readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          if (entry.name === 'data' || entry.name === 'assets' || entry.name === '.split-tmp') continue;
          await auditBareImports(fullPath);
        } else if (entry.isFile() && (entry.name.endsWith('.js') || entry.name.endsWith('.mjs'))) {
          const content = await readFile(fullPath, 'utf8');
          for (const pattern of BARE_SUPABASE_PATTERNS) {
            pattern.lastIndex = 0;
            if (pattern.test(content)) {
              offenders.push(path.relative(dist, fullPath));
              break;
            }
          }
        }
      }
    }
    await auditBareImports(dist);
    if (offenders.length > 0) {
      console.error('BUILD FAIL: bare @supabase/supabase-js import statements found in browser-served modules:');
      for (const f of offenders) console.error(`  - ${f}`);
      process.exit(1);
    }
    console.log('build: verified 0 bare @supabase/supabase-js import statements in dist');
  }
}

// ── Replace sw.js with a self-unregistering kill switch ────────────────
// The service worker was removed in v0.27.1 because stale caches served
// raw source files with bare package imports the browser cannot resolve.
// We overwrite sw.js with a minimal script that immediately unregisters
// itself and clears all caches. This ensures that even if an old SW is
// still active and fetches this file for update detection, installing it
// will clean up all stale caches and remove the SW registration entirely.
{
  const swPath = path.join(dist, 'sw.js');
  const killScript = [
    '// sw.js — self-unregistering kill switch (v0.27.1+)',
    '// The service worker was removed because stale caches served raw',
    '// source files with bare package imports the browser cannot resolve.',
    '// This file exists only to ensure old SWs update to a version that',
    '// immediately unregisters itself and clears all caches.',
    '',
    'self.addEventListener("install", (e) => {',
    '  e.waitUntil(self.skipWaiting());',
    '});',
    '',
    'self.addEventListener("activate", (e) => {',
    '  e.waitUntil((async () => {',
    '    const keys = await caches.keys();',
    '    await Promise.all(keys.map((k) => caches.delete(k)));',
    '    await self.registration.unregister();',
    '    const clients = await self.clients.claim();',
    '    const allClients = await self.clients.matchAll();',
    '    allClients.forEach((c) => c.navigate(c.url));',
    '  })());',
    '});',
    '',
  ].join('\n');
  await writeFile(swPath, killScript);
  console.log('build: wrote self-unregistering sw.js kill switch');
}

