/**
 * Version generator — single source of truth.
 * Reads config/release-identity.json and emits a version module for both Node and browser.
 *
 * Usage:
 *   node scripts/generate-version.mjs                    # writes packages/shared/src/version.mjs
 *   node scripts/generate-version.mjs --browser <path>   # writes browser version.js
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const identity = JSON.parse(await readFile(path.join(root, 'config/release-identity.json'), 'utf8'));

const versionData = {
  labVersion: identity.version,
  engineVersion: identity.engineVersion,
  rulesVersion: identity.rulesVersion,
  officialRulesVersion: identity.officialRulesVersion,
  schemaVersion: identity.coreSchemaVersion,
  decisionTraceSchemaVersion: identity.decisionTraceSchemaVersion,
  analyticsSchemaVersion: identity.analyticsSchemaVersion,
  telemetrySchemaVersion: identity.telemetrySchemaVersion,
  // REPLAY_DATA_VERSION is the data format version embedded in replay artifacts.
  // It is intentionally separate from the release version and only changes when
  // the replay data format itself changes (breaking backward compatibility).
  replayDataVersion: identity.replayDataVersion
};

const isBrowser = process.argv.includes('--browser');
const browserIdx = process.argv.indexOf('--browser');
const browserPath = browserIdx >= 0 && process.argv[browserIdx + 1] && !process.argv[browserIdx + 1].startsWith('--')
  ? process.argv[browserIdx + 1]
  : path.join(root, 'apps/lab-web/src/version.js');

if (isBrowser) {
  // Browser version — plain JS, no imports needed
  const browserCode = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const LAB_VERSION = ${JSON.stringify(versionData.labVersion)};
export const ENGINE_VERSION = ${JSON.stringify(versionData.engineVersion)};
export const RULES_VERSION = ${JSON.stringify(versionData.rulesVersion)};
export const OFFICIAL_RULES_VERSION = ${JSON.stringify(versionData.officialRulesVersion)};
export const SCHEMA_VERSION = ${JSON.stringify(versionData.schemaVersion)};
`;
  await writeFile(browserPath, browserCode);
  console.log(`generate-version: wrote browser version to ${browserPath} (v${versionData.labVersion})`);
} else {
  // Node version — part of @intrilex/shared
  const nodeCode = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const LAB_VERSION = ${JSON.stringify(versionData.labVersion)};
export const ENGINE_VERSION = ${JSON.stringify(versionData.engineVersion)};
export const RULES_VERSION = ${JSON.stringify(versionData.rulesVersion)};
export const OFFICIAL_RULES_VERSION = ${JSON.stringify(versionData.officialRulesVersion)};
export const SCHEMA_VERSION = ${JSON.stringify(versionData.schemaVersion)};
export const DECISION_TRACE_SCHEMA_VERSION = ${JSON.stringify(versionData.decisionTraceSchemaVersion)};
export const ANALYTICS_SCHEMA_VERSION = ${JSON.stringify(versionData.analyticsSchemaVersion)};
export const TELEMETRY_SCHEMA_VERSION = ${JSON.stringify(versionData.telemetrySchemaVersion)};
export const REPLAY_DATA_VERSION = ${JSON.stringify(versionData.replayDataVersion)};
`;
  const outputPath = path.join(root, 'packages/shared/src/version.mjs');
  await writeFile(outputPath, nodeCode);
  console.log(`generate-version: wrote Node version to ${outputPath} (v${versionData.labVersion})`);
}
