import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),release=path.join(root,'release'),packageJson=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')),version=packageJson.version;
const zipName=`Intrilex_Simulation_Lab_v${version}_Mechanics_Observatory.zip`,zip=path.join(release,zipName);
await mkdir(release,{recursive:true});
for(const name of await readdir(release))if(/^Intrilex_Simulation_Lab_v.+\.zip(?:\.sha256)?$/.test(name))try{await rm(path.join(release,name),{force:true});}catch{/* Windows may lock files briefly; best-effort cleanup */}
// SEC-01: Secret containment scan — fail-closed before packaging.
// No secrets, tokens, or private keys may be present in tracked files or artifacts.
let r=spawnSync(process.execPath,['scripts/secret-containment-scan.mjs'],{cwd:root,stdio:'inherit'});if(r.status!==0){console.error('SEC-01 FAIL: secret containment scan failed — refusing to package release');process.exit(r.status??1);}
r=spawnSync(process.execPath,['scripts/package-engine-patch.mjs'],{cwd:root,stdio:'inherit'});if(r.status!==0)process.exit(r.status??1);
await copyFile(path.join(root,'reports/BUILD_PROOF.md'),path.join(release,'BUILD_PROOF.md'));
// IRX-C05: Generate manifest BEFORE creating ZIP so it is embedded in the archive.
// Previously the manifest was generated after the ZIP, so it was never in the archive,
// making the extracted-verification step fail to find it.
r=spawnSync(process.execPath,['scripts/manifest.mjs','generate'],{cwd:root,stdio:'inherit'});if(r.status!==0)process.exit(r.status??1);
const python=process.platform==='win32'?'python':'python3';
// IRX-C01: Exclude .env and all secret-bearing files from the release archive.
// The secret-containment-scan only scans git-tracked files; .env is gitignored
// and therefore "compliant" — but deterministic_zip.py archives the entire workspace.
// Without these exclusions, live Supabase credentials ship in the release ZIP.
const SECRET_FILE_EXCLUSIONS=['.env','.env.local','.env.*.local','neocities.config.js','*.pem','*.key','*.p12','*.pfx','*.keystore'];
// IRX-M39: Exclude runtime SQLite database files and WAL/SHM sidecars.
// These are generated during testing/development and must never ship in the release.
const RUNTIME_DB_EXCLUSIONS=['*.sqlite','*.sqlite-wal','*.sqlite-shm','*.db','*.db-wal','*.db-shm','terminal-outbox.sqlite*','match-store.sqlite*'];
// IRX-M39: Exclude other runtime state, temp files, and debug residue.
const RUNTIME_STATE_EXCLUSIONS=['supabase/.temp/*','*.tmp','*.bak','*.log'];
// IRX-M31: Exclude generated reports and build artifacts that bloat the archive.
// These are regenerated by verification scripts and don't need to ship in the
// source distribution. The release manifest and certification are kept.
const BLOAT_EXCLUSIONS=[
  'reports/browser-ui-smoke.json',
  'reports/browser-e2e-certification.json',
  'reports/browser-network-e2e.json',
  'reports/browser-parity.json',
  'reports/build-determinism.json',
  'reports/engine-patch-integrity.json',
  'reports/vendor-integrity.json',
  'reports/capability-manifest.json',
  'reports/package-determinism.json',
  'reports/extracted-verification-report.json',
  'reports/self-audit.quick.json',
  'apps/lab-web/dist/*',
  'release/Intrilex_Simulation_Lab_v*.zip',
  'release/Intrilex_Simulation_Lab_v*.zip.sha256',
  'release/Intrilex_Engine_v*.zip',
  'release/Intrilex_Engine_v*.zip.sha256',
  'release/extracted-verification-report.json',
  'release/package-determinism.json',
  'release/RELEASE_INTEGRITY.md',
];
r=spawnSync(python,[path.join(root,'scripts/deterministic_zip.py'),root,zip,...SECRET_FILE_EXCLUSIONS,...RUNTIME_DB_EXCLUSIONS,...RUNTIME_STATE_EXCLUSIONS,...BLOAT_EXCLUSIONS,'.git/*','runtime/campaign-segments*/*','runtime/campaign-replays*/*','node_modules/*','*/node_modules/*','package-lock.json'],{cwd:root,stdio:'inherit'});if(r.status!==0)process.exit(r.status??1);
// IRX-C01: Post-zip secret scan — verify no secrets leaked into the final archive.
r=spawnSync(process.execPath,['scripts/scan-archive-secrets.mjs',zip],{cwd:root,stdio:'inherit'});if(r.status!==0){console.error('SEC-01 FAIL: secret detected in release archive — refusing to package');process.exit(r.status??1);}
const digest=createHash('sha256').update(await readFile(zip)).digest('hex');await writeFile(`${zip}.sha256`,`${digest}  ${zipName}\n`);
// IRX-C05: Manifest was already generated before ZIP creation (embedded in archive).
// Now read it for certification binding.
const manifest=JSON.parse(await readFile(path.join(release,'RELEASE_MANIFEST.json'),'utf8'));
const versionedManifestPath=path.join(release,`v${version}-release-manifest.json`);
await writeFile(versionedManifestPath,JSON.stringify(manifest,null,2)+'\n');
// IRX-M26: Derive ACTUAL pass/fail/skip/cancelled counts from self-audit.json.
// Previously this fabricated passed=totalTests (always 100% pass) by parsing only
// the test count from a report string. Now we use the real counts from the audit.
const selfAudit=JSON.parse(await readFile(path.join(root,'reports/self-audit.json'),'utf8'));
const tr=selfAudit.testResults??{};
const totalTests=tr.totalTests??0;
const totalPass=tr.totalPass??0;
const totalFail=tr.totalFail??0;
const totalSkip=tr.totalSkip??0;
const totalCancelled=tr.totalCancelled??0;
// IRX-M26: Refuse to certify a release with any test failures.
if(totalFail>0){console.error(`CERTIFICATION FAIL: ${totalFail} test failure(s) in self-audit — refusing to certify release`);process.exit(1);}
const certification={schemaVersion:'1.0.0',releaseVersion:version,engineVersion:manifest.engineVersion,rulesVersion:manifest.rulesVersion,releaseZip:{name:zipName,sha256:digest},testResults:{passed:totalPass,totalTests,failed:totalFail,skipped:totalSkip,cancelled:totalCancelled},manifestHash:createHash('sha256').update(await readFile(versionedManifestPath)).digest('hex')};
await writeFile(path.join(release,`v${version}-certification.json`),JSON.stringify(certification,null,2)+'\n');
console.log(`PACKAGE PASS: ${digest}`);
